- src/modules/external/entreprise-api.service.ts
- src/modules/external/interfaces/RnaInterface.ts
- src/modules/external/interfaces/SiretDataInterface.ts
- src/modules/leCompteAsso/@types/ILeCompteAssoPartialRequestEntity.ts
- src/modules/leCompteAsso/leCompteAsso.service.ts
- src/modules/leCompteAsso/repositories/leCompteAsso.repository.ts
- src/modules/osiris/interfaces/cli/osiris.cli.contoller.ts
- src/modules/osiris/osiris.service.ts
- src/modules/osiris/repository/osiris.repository.ts
- src/modules/search/@types/ILegalInformations.ts
- src/modules/search/search.service.ts
> Utiliser les Types pluton qu'un type par défaut Notifications

- package-lock.json
- package.json
- src/cli.ts
- src/configurations/mail.conf.ts
- src/index.ts
- src/modules/mail-notifier/interfaces/cli/mail-notifier.cli.controller.ts
- src/modules/mail-notifier/mail-notifier.service.ts
- src/modules/mail-notifier/providers/@types/IProvider.ts
- src/modules/mail-notifier/providers/nodemailer.provider.ts
- src/modules/mail-notifier/providers/provider-factory.ts
- tests/modules/mail-notifier/mail-notifier-service.test.ts
> Ajout d'un module qui permet d'envoyer des mails

- src/modules/user/interfaces/http/UserController.ts
- src/modules/user/user.service.ts
- tests/modules/user/interfaces/http/UserController.test.ts
> feat: add user change password

- src/authentication/authentication.ts
- src/modules/user/interfaces/http/AuthentificationController.ts
- src/modules/user/repositoies/user.repository.ts
- src/modules/user/user.service.ts
- src/server.ts
- tests/authentication/authentication.test.ts
> Ajout d'une route pour la déconnexion

- src/modules/mail-notifier/mail-notifier.service.ts
- tests/modules/mail-notifier/mail-notifier-service.test.ts
j'ai changé le contenu des mails, micros corrections d'orthographe
> ortho correction in mail

- .github/workflows/api.yml
- packages/api/jest.config.ts
- packages/api/src/modules/search/interfaces/http/SearchController.ts
- packages/api/src/modules/search/search.service.ts
- packages/api/src/shared/Validators.ts
- packages/api/tests/modules/search/search.service.test.ts
- packages/front/src/modules/search/SearchController.ts
- packages/front/src/shared/apiDatasub.service.ts
- packages/front/src/views/home/home.ejs
> Recherche d'une asso par siren

- packages/api/src/modules/associations/associations.service.ts
- packages/api/src/modules/associations/interfaces/AssociationsProvider.ts
- packages/api/src/modules/providers/dataEntreprise/dataEntreprise.service.ts
- packages/api/src/modules/providers/leCompteAsso/leCompteAsso.service.ts
- packages/api/src/modules/providers/osiris/osiris.service.ts
- packages/api/src/modules/search/search.service.ts
> fix(api): search asso with rna

- packages/front/views/auth/forget-password/index.ejs
> mdp oublié orthographe

- packages/front/views/etablissement/components/etablissement/informations_banquaire.ejs
> Info bancaires

- packages/front/views/etablissement/components/etablissement/contacts.ejs
> orthographe

- lerna.json
- packages/api/package-lock.json
- packages/api/package.json
- packages/dto/package.json
- packages/front/package.json
- packages/front/views/auth/login/login.ejs
> Ajouts d'un lien pour l'inscription

- packages/api/src/modules/providers/chorus/@types/IChorusIndexedInformations.ts
- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.ts
- packages/api/src/modules/providers/chorus/chorus.parser.ts
- packages/api/src/modules/providers/chorus/entities/ChorusLineEntity.ts
- packages/api/src/modules/search/interfaces/http/dto/AssociationDto.ts
- packages/api/src/modules/search/interfaces/http/dto/EtablissmentDto.ts
- packages/api/src/modules/search/search.service.ts
- packages/api/src/modules/versements/interfaces/Versement.ts
- packages/api/src/modules/versements/versements.service.ts
- packages/api/tests/modules/providers/chorus/chorus.service.test.ts
- packages/api/tests/modules/versements/versements.service.test.ts
- packages/dto/search/AssociationDto.ts
- packages/dto/search/EtablissementDtoResponse.ts
- packages/dto/search/EtablissmentDto.ts
- packages/dto/search/VersementDto.ts
- packages/front/src/index.ts
- packages/front/src/modules/association/AssociationService.ts
- packages/front/src/modules/association/interfaces/http/AssociationController.ts
- packages/front/src/modules/etablissement/EtablissementService.ts
- packages/front/src/modules/etablissement/interfaces/http/EtablissementController.ts
- packages/front/src/modules/global_components/index.ts
- packages/front/src/modules/global_components/versements/index.ts
- packages/front/views/association/index.ejs
- packages/front/views/etablissement/index.ejs
- packages/front/views/global_components/versements/index.ejs
- packages/front/views/global_components/versements/versements_table.ejs
> Ajout des parties versements dans les pages Asso et Etablissement

- packages/api/src/modules/mail-notifier/mail-notifier.service.ts
Quelques révisions du mail (mise en page revue + ajout du lien de réservation de démo)
Grazie mille !
> Mail inscription - Mise à jour

- packages/front/views/global_components/demandes_subventions/totals.ejs
> refactor(front): merge subvention by status

- packages/front/views/auth/login/login.ejs
> Coquillette

- packages/front/src/shared/helpers/CurrencyHelper.ts
- packages/front/src/shared/helpers/EJSHelper.ts
- packages/front/views/global_components/demandes_subventions/index.ejs
- packages/front/views/global_components/versements/index.ejs
> feat(front): add space to currency

- packages/front/views/global_components/demandes_subventions/index.ejs
- packages/front/views/global_components/versements/index.ejs
- packages/front/views/global_components/versements/versements_table.ejs
> feat(front): show message when data not found in versement and demande_subvention

- packages/api/src/configurations/mail.conf.ts
- packages/api/src/modules/mail-notifier/providers/nodemailer.provider.ts
- packages/api/tests/modules/mail-notifier/mail-notifier-service.test.ts
> chore(api): add mail logger

- packages/api/src/modules/providers/datagouv/interfaces/cli/datagouv.cli.controller.ts
- packages/api/src/modules/providers/datagouv/repositories/entreprise_siren.repository.ts
- packages/api/tests/modules/providers/datagouv/interfaces/cli/DataGouvCliController.test.ts
> Ajout des tests pour la cli du provider datagouv

- packages/tools/README.md
- packages/tools/package.json
> feat(tools): init learna package

- packages/api/src/modules/user/interfaces/http/AuthentificationController.ts
- packages/api/tests/modules/user/interfaces/http/AuthentificationController.test.ts
- packages/dto/auth/ResetPasswordDtoResponse.ts
- packages/dto/index.ts
- packages/front/src/modules/auth/AuthService.ts
- packages/front/src/modules/auth/interfaces/http/AuthController.ts
- packages/front/src/shared/apiDatasub.service.ts
- packages/front/views/auth/reset-password/resetPassword.ejs
> Meillieur gestion des erreurs dans le reset password

- packages/front/views/auth/login/login.ejs
- packages/front/views/header.ejs
> feat(front): display info when JS disabled

- packages/api/src/configurations/auth.conf.ts
- packages/api/src/modules/user/interfaces/http/AuthentificationController.ts
- packages/api/src/modules/user/user.service.ts
- packages/dto/auth/SignupDtoResponse.ts
- packages/dto/index.ts
- packages/dto/package.json
- packages/front/src/index.ts
- packages/front/src/middlewares/auth.middleware.ts
- packages/front/src/modules/auth/AuthService.ts
- packages/front/src/modules/auth/interfaces/http/AuthController.ts
- packages/front/src/shared/apiDatasub.service.ts
- packages/front/views/auth/login/login.ejs
- packages/front/views/auth/signup/index.ejs
- packages/front/views/header.ejs
> Formulaire d'inscription

- packages/api/src/cli.ts
- packages/api/src/modules/providers/chorus/interfaces/cli/chorus.cli.controller.ts
> Préparation pour l'import des nouveau fichier chorus

- packages/api/migrations/20220427141655-recompute-osiris-date.js
- packages/api/src/modules/providers/osiris/entities/OsirisRequestEntity.ts
- packages/api/src/modules/providers/osiris/repositories/osiris.repository.ts
> fix(api): fix osiris date exercice debut to utc date

- packages/api/src/modules/associations/@types/Association.ts
- packages/api/src/modules/etablissements/@types/Etablissement.ts
- packages/api/src/modules/providers/gispro/gispro.service.ts
- packages/api/src/modules/search/interfaces/http/SearchController.ts
- packages/api/src/modules/stats/interfaces/http/StatsController.ts
- packages/api/tests/modules/open-data/providers/ProviderController.spec.ts
- packages/dto/search/AssociationDto.ts
- packages/dto/search/EtablissmentDto.ts
- packages/dto/shared/Adresse.ts
- packages/dto/shared/InformationBancaire.ts
- packages/dto/shared/Personne.ts
> chore(api): fix tsoa documentation

- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.repository.ts
> Régler les soucis eslint

- packages/api/src/modules/providers/chorus/interfaces/cli/chorus.cli.controller.ts
- packages/api/src/modules/providers/datagouv/interfaces/cli/datagouv.cli.controller.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
- packages/api/src/modules/providers/osiris/interfaces/cli/osiris.cli.contoller.ts
- packages/api/src/shared/CliController.test.ts
- packages/api/src/shared/CliController.ts
- packages/api/tests/modules/providers/chorus/interfaces/cli/chorus.cli.controller.test.ts
- packages/api/tests/modules/providers/datagouv/interfaces/cli/DataGouvCliController.test.ts
> refactor(api): mv parse in CliController

- packages/front/views/association/index.ejs
- packages/front/views/auth/login/login.ejs
- packages/front/views/auth/reset-password/resetPassword.ejs
- packages/front/views/auth/signup/index.ejs
- packages/front/views/global_components/demandes_subventions/details.ejs
- packages/front/views/global_components/demandes_subventions/index.ejs
- packages/front/views/global_components/versements/index.ejs
Faire un tag de version avant de merger
> fix(front): fix ortho

- packages/front/views/header.ejs
> feat(front): add pipe drive chat bot

- packages/api/package-lock.json
- packages/api/src/authentication/express.auth.hooks.ts
- packages/api/src/modules/user/interfaces/http/AuthentificationController.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/authentication/express.auth.hooks.test.ts
- packages/api/tests/modules/user/interfaces/http/AuthentificationController.test.ts
- packages/api/tests/modules/user/user.service.test.ts
- packages/dto/auth/LoginDtoResponse.ts
- packages/front/package-lock.json
- packages/front/src/modules/auth/AuthService.ts
- packages/front/src/modules/auth/interfaces/http/AuthController.ts
- packages/front/views/auth/login/login.ejs
> Erreur à la connection

- packages/api/src/modules/stats/interfaces/http/StatsController.ts
- packages/api/src/modules/stats/repositories/__snapshots__/statsRepository.test.ts.snap
- packages/api/src/modules/stats/repositories/statsRepository.test.ts
- packages/api/src/modules/stats/repositories/statsRepository.ts
- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/tests/modules/stats/interfaces/http/StatsController.test.ts
- packages/dto/index.ts
- packages/dto/stats/StatsRequestsMedianDto.ts
> Ajouter une route de stats pour la median des requests

- packages/front/src/shared/helpers/EJSHelper.ts
- packages/front/src/shared/helpers/PhoneHelper.ts
- packages/front/static/css/custom.css
- packages/front/views/association/components/association/index.ejs
- packages/front/views/association/components/card_etablissement.ejs
- packages/front/views/etablissement/components/association/index.ejs
- packages/front/views/etablissement/components/etablissement/contacts.ejs
- packages/front/views/etablissement/components/etablissement/index.ejs
- packages/front/views/etablissement/components/etablissement/informations_banquaire.ejs
- packages/front/views/etablissement/components/etablissement/representants_legaux.ejs
- packages/front/views/global_components/demandes_subventions/details.ejs
- packages/front/views/global_components/versements/versements_table.ejs
> Afficher un - quand une donnée est manquante

- packages/front/src/shared/helpers/AmountHelper.ts
- packages/front/src/shared/helpers/CurrencyHelper.ts
- packages/front/src/shared/helpers/EJSHelper.ts
- packages/front/views/global_components/demandes_subventions/details.ejs
- packages/front/views/global_components/demandes_subventions/index.ejs
- packages/front/views/global_components/versements/index.ejs
- packages/front/views/global_components/versements/versements_table.ejs
> Ajouter un € à chaque montant

- packages/api/README.md
> feat(api): update README

- packages/api/migrations/20220527070446-replace-siret-to-siren-association-names.js
- packages/api/src/modules/providers/dataEntreprise/dataEntreprise.service.ts
- packages/api/src/modules/providers/leCompteAsso/leCompteAsso.service.ts
- packages/api/src/modules/providers/osiris/osiris.service.ts
> fix(api): fix siret as siren in association-name

- packages/api/src/cli.ts
- packages/api/src/modules/providers/subventia/@types/ISubventiaIndexedInformation.ts
- packages/api/src/modules/providers/subventia/__fixtures__/entity.ts
- packages/api/src/modules/providers/subventia/entities/SubventiaRequestEntity.ts
- packages/api/src/modules/providers/subventia/interfaces/subventia.cli.controller.test.ts
- packages/api/src/modules/providers/subventia/interfaces/subventia.cli.controller.ts
- packages/api/src/modules/providers/subventia/repositories/subventia.repository.test.ts
- packages/api/src/modules/providers/subventia/repositories/subventia.repository.ts
- packages/api/src/modules/providers/subventia/subventia.parser.test.ts
- packages/api/src/modules/providers/subventia/subventia.parser.ts
- packages/api/src/modules/providers/subventia/subventia.service.test.ts
- packages/api/src/modules/providers/subventia/subventia.service.ts
- packages/api/src/shared/CliController.test.ts
- packages/api/src/shared/CliController.ts
- packages/api/src/shared/CliLogger.test.ts
- packages/api/src/shared/CliLogger.ts
- packages/api/src/shared/MigrationRepository.ts
> Ajout d'un parser subventia

- packages/api/migrations/20220607103015-fix-osiris-status-null.js
- packages/api/src/modules/providers/osiris/entities/OsirisRequestEntity.ts
> fix(api): add 'Etat dossier' in path for osirisRequestEntity status

- packages/api/migrations/20220607092507-lower-case-user.js
- packages/api/src/modules/user/repositoies/user.repository.ts
- packages/api/src/modules/user/user.migration.test.ts
- packages/api/src/modules/user/user.migrations.ts
- packages/api/src/modules/user/user.service.ts
> feat(api): user email to lower case

- packages/front/src/modules/admin/interfaces/http/AdminController.ts
- packages/front/static/css/custom.css
- packages/front/views/admin/create-user.ejs
- packages/front/views/admin/domain.ejs
- packages/front/views/admin/index.ejs
- packages/front/views/admin/list-users.ejs
> 274 admin show user by domaine name

- packages/front/static/css/custom.css
- packages/front/views/admin/list-users.ejs
- packages/front/views/admin/listUsers_controller.js
- packages/front/views/document_controller.js
- packages/front/views/header.ejs
> 275 number of users

- CHANGELOG.md
- lerna.json
- packages/api/CHANGELOG.md
- packages/api/migrations/20220620093606-current-osiris-import-is-2021.js
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/modules/providers/osiris/@types/IOsirisActionsInformations.ts
- packages/api/src/modules/providers/osiris/@types/IOsirisEvaluationsInformations.ts
- packages/api/src/modules/providers/osiris/@types/IOsirisRequestInformations.ts
- packages/api/src/modules/providers/osiris/adapters/OsirisRequestAdapter.ts
- packages/api/src/modules/providers/osiris/interfaces/cli/osiris.cli.contoller.ts
- packages/api/src/modules/providers/osiris/osiris.migrations.ts
- packages/api/src/modules/providers/osiris/osiris.parser.ts
- packages/api/src/modules/providers/osiris/repositories/osiris.evaluation.repository.ts
- packages/api/tests/modules/associations/__snapshots__/associations.spec.ts.snap
- packages/api/tests/modules/providers/osiris/__fixtures__/entity.ts
- packages/api/tests/modules/providers/osiris/interfaces/cli/osiris.cli.controller.test.ts
- packages/api/tests/modules/providers/osiris/osiris.parser.test.ts
- packages/api/tests/modules/providers/osiris/osiris.service.test.ts
- packages/api/tests/modules/search/__snapshots__/search.spec.ts.snap
- packages/api/tests/modules/subventions/__snapshots__/subventions.spec.ts.snap
- packages/dto/CHANGELOG.md
- packages/dto/package-lock.json
- packages/dto/package.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/tools/CHANGELOG.md
- packages/tools/package-lock.json
- packages/tools/package.json
> fix(api): fix wrong year on osiris data

- CHANGELOG.md
- packages/api/src/modules/associations/associations.service.test.ts
- packages/api/src/modules/associations/associations.service.ts
- packages/api/src/modules/associations/interfaces/http/AssociationController.test.ts
- packages/api/src/modules/associations/interfaces/http/AssociationController.ts
- packages/api/src/modules/etablissements/etablissements.service.test.ts
- packages/api/src/modules/etablissements/etablissements.service.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.test.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.ts
- packages/api/src/modules/providers/avisSituationInsee/avisSituationInsee.service.test.ts
- packages/api/src/modules/providers/avisSituationInsee/avisSituationInsee.service.ts
- packages/api/src/modules/providers/index.ts
- packages/api/tests/modules/open-data/providers/__snapshots__/providers.spec.ts.snap
- packages/front/CHANGELOG.md
> 322 add routes getting docs

- CHANGELOG.md
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/configurations/apis.conf.ts
- packages/api/src/modules/providers/apiEntreprise/apiEntreprise.service.test.ts
- packages/api/src/modules/providers/apiEntreprise/apiEntreprise.service.ts
- packages/front/CHANGELOG.md
> feat(api): add service for api entreprise

- packages/front/.prettierrc
- packages/front/svelte/App.svelte
- packages/front/svelte/components/CardDocuments.svelte
- packages/front/svelte/components/ErrorAlert.svelte
- packages/front/svelte/components/Spinner.svelte
- packages/front/svelte/components/TitleWithData.svelte
- packages/front/svelte/dsfr/Alert.svelte
- packages/front/svelte/dsfr/Breadcrumb.svelte
- packages/front/svelte/dsfr/Card.svelte
- packages/front/svelte/dsfr/Tab.svelte
- packages/front/svelte/dsfr/TabContent.svelte
- packages/front/svelte/dsfr/Tabs.svelte
- packages/front/svelte/global.css
- packages/front/svelte/helpers/visibilityHelper.js
- packages/front/svelte/shared/Auth.svelte
- packages/front/svelte/shared/Footer.svelte
- packages/front/svelte/shared/Header.svelte
- packages/front/svelte/shared/Router.svelte
- packages/front/svelte/shared/Theme.svelte
- packages/front/svelte/store/user.store.js
- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/association/association.adapter.js
- packages/front/svelte/views/association/association.helper.js
- packages/front/svelte/views/association/association.service.js
- packages/front/svelte/views/association/components/Documents.svelte
- packages/front/svelte/views/association/components/Etablissements.svelte
- packages/front/svelte/views/association/components/InfosLegales.svelte
- packages/front/svelte/views/association/components/TabsAsso.svelte
- packages/front/views/header.ejs
> 320 add documents svelte

- packages/front/views/admin/list-users.ejs
> fix(front): spelling correction

- packages/front/package-lock.json
- packages/front/package.json
- packages/front/static/svelte-index.html
- packages/front/views/footer.ejs
Close #351 
Je sais pas trop si c'était la seule chose à faire.
Je ne sais pas non plus comment tester, je suppose qu'il va falloir être en prod car le Dashboard matomo ne doit pas avoir de sous domaine preprod ?
> feat(front): enable matomo with datasub id

- packages/front/svelte/components/CardDocuments.svelte
- packages/front/svelte/views/association/components/Etablissements.svelte
- packages/front/svelte/views/association/components/TabsAsso.svelte
> feat(front): change title of etablissements and target blank on dl document

- packages/front/svelte/dsfr/Modal.svelte
- packages/front/svelte/views/association/association.service.js
- packages/front/svelte/views/association/components/ProviderModal.svelte
- packages/front/svelte/views/association/components/TabsAsso.svelte
- packages/front/svelte/views/association/components/dashboard/Dashboard.svelte
> feat(front): add modals providers

- packages/front/svelte/components/TableCell.svelte
- packages/front/svelte/components/TableHead.svelte
- packages/front/svelte/dsfr/Modal.svelte
- packages/front/svelte/helpers/dataHelper.js
- packages/front/svelte/views/association/components/SubventionInfoModal.svelte
- packages/front/svelte/views/association/components/SubventionTable.svelte
- packages/front/svelte/views/association/components/VersementTable.svelte
- packages/front/svelte/views/association/components/VersementsInfoModal.svelte
> feat(front): add versements and subvention modals

- packages/api/src/modules/providers/chorus/chorus.service.ts
- packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.repository.ts
- packages/api/src/modules/providers/gispro/gispro.service.ts
- packages/api/src/modules/providers/gispro/repositories/gispro.repository.ts
- packages/api/src/modules/providers/leCompteAsso/leCompteAsso.service.ts
- packages/api/src/modules/providers/leCompteAsso/repositories/leCompteAsso.repository.ts
- packages/api/src/modules/providers/osiris/osiris.service.ts
- packages/api/src/modules/providers/osiris/repositories/osiris.action.repository.test.ts
- packages/api/src/modules/providers/osiris/repositories/osiris.action.repository.ts
- packages/api/src/modules/providers/osiris/repositories/osiris.evaluation.repository.ts
- packages/api/src/modules/providers/osiris/repositories/osiris.request.repository.ts
- packages/api/src/modules/providers/subventia/repositories/subventia.repository.test.ts
- packages/api/src/modules/providers/subventia/repositories/subventia.repository.ts
- packages/api/src/modules/providers/subventia/subventia.service.test.ts
- packages/api/src/modules/providers/subventia/subventia.service.ts
- packages/api/src/modules/user/repositoies/user-reset.repository.ts
- packages/api/src/modules/user/repositoies/user.repository.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/modules/providers/chorus/chorus.service.test.ts
- packages/api/tests/modules/subventions/subventions.spec.ts
> 287 remove find after create

- packages/front/svelte/helpers/dataHelper.js
- packages/front/svelte/helpers/dateHelper.js
- packages/front/svelte/shared/Router.svelte
- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/association/components/InfosLegales.svelte
- packages/front/svelte/views/association/components/SubventionTable.svelte
- packages/front/svelte/views/association/components/VersementTable.svelte
- packages/front/svelte/views/association/components/VersementsInfoModal.svelte
- packages/front/svelte/views/association/components/dashboard/Dashboard.core.js
- packages/front/svelte/views/association/components/dashboard/Dashboard.svelte
> feat(front): update dashboard from bizdev comments

- packages/front/nodemon.json
- packages/front/svelte/components/TableCell.svelte
- packages/front/svelte/components/TableHead.svelte
- packages/front/svelte/dsfr/Table.svelte
- packages/front/svelte/global.css
> fix(front): handle dark mode for tables

- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
> test(api): add test on fonjep service for check if repository have been called

- packages/front/svelte/App.svelte
- packages/front/svelte/dsfr/Button.svelte
- packages/front/svelte/dsfr/GenericModal.svelte
- packages/front/svelte/store/modal.store.js
- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/svelte/views/admin/users/composents/RemoveUserModal.svelte
- packages/front/svelte/views/admin/users/composents/TableUsers.svelte
- packages/front/svelte/views/association/components/ProviderModal.svelte
- packages/front/svelte/views/association/components/VersementTable.svelte
- packages/front/svelte/views/association/components/VersementsInfoModal.svelte
- packages/front/svelte/views/association/components/dashboard/Dashboard.svelte
> 337 unique modal

- packages/api/src/modules/providers/chorus/entities/ChorusLineEntity.ts
- packages/api/tests/modules/providers/chorus/chorus.parser.test.ts
> feat(api): update parser for new data 2022

- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/adapters/__snapshots__/ApiAssoDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/dataEntreprise/adapters/AssociationDtoAdapter.ts
- packages/api/src/modules/providers/dataEntreprise/adapters/EntrepriseDtoAdapter.ts
- packages/dto/search/Association.ts
- packages/front/svelte/dsfr/Table.svelte
- packages/front/svelte/global.css
- packages/front/svelte/views/association/association.adapter.js
- packages/front/svelte/views/association/components/InfosLegales.svelte
> 407 separation rna siren suite

- packages/front/package-lock.json
- packages/front/src/modules/home/interfaces/http/HomeController.ts
- packages/front/svelte/App.svelte
- packages/front/svelte/shared/Router.svelte
- packages/front/svelte/views/home/Home.svelte
> feat(front): move home page to svelte

- packages/api/migrations/20220926145419-rename-fonjep-collection.js
- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.test.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.subvention.repository.ts
- packages/api/tests/modules/associations/associations.spec.ts
- packages/api/tests/modules/open-data/providers/providers.spec.ts
- packages/api/tests/modules/subventions/subventions.spec.ts
> feat(api): rename fonjep collection to fonjepSubvention

- packages/front/svelte/components/CardDocuments.svelte
> feat(front): make click on icon of CardDocument active

- packages/api/src/authentication/authentication.test.ts
- packages/api/src/authentication/authentication.ts
- packages/api/src/authentication/express.auth.hooks.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/server.ts
- packages/api/tests/authentication/express.auth.hooks.test.ts
> feat(api): manage user in current request

- packages/front/src/index.ts
- packages/front/static/css/custom.css
- packages/front/static/svelte-index.html
- packages/front/svelte/App.svelte
- packages/front/svelte/components/Matomo.svelte
- packages/front/svelte/shared/Header.svelte
- packages/front/views/footer.ejs
- packages/front/views/header.ejs
> feat(front): disable matomo

- packages/api/migrations/20221003131234-addSearchStatInUser.js
- packages/api/src/authentication/authentication.test.ts
- packages/api/src/authentication/authentication.ts
- packages/api/src/authentication/express.auth.hooks.ts
- packages/api/src/middlewares/StatsSearchMiddleware.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/user/entities/User.ts
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/server.ts
- packages/api/tests/authentication/express.auth.hooks.test.ts
- packages/api/tests/modules/user/repositories/user.repository.test.ts
- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> feat(api): add stats to user

- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
- packages/api/src/modules/providers/dauphin/dto/DauphinSubventionDto.ts
- packages/front/svelte/views/association/components/SubventionInfoModal.svelte
- packages/front/svelte/views/association/components/SubventionTable.svelte
> fix(front, api): clean dauphin and subvention table

- packages/api/migrations/20221005131437-addSignupDateInUser.js
- packages/api/src/authentication/authentication.test.ts
- packages/api/src/modules/user/entities/User.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/authentication/express.auth.hooks.test.ts
- packages/api/tests/modules/user/repositories/user.repository.test.ts
- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> feat(front,api): add signup date to user

- packages/api/migrations/20221010094231-lastSearchDate.js
- packages/api/src/authentication/authentication.test.ts
- packages/api/src/middlewares/StatsSearchMiddleware.ts
- packages/api/src/modules/user/entities/User.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/authentication/express.auth.hooks.test.ts
- packages/api/tests/modules/user/repositories/user.repository.test.ts
- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> 445 last activity by user

- packages/front/svelte/dsfr/Breadcrumb.svelte
- packages/front/svelte/dsfr/Card.svelte
- packages/front/svelte/helpers/textHelper.js
- packages/front/svelte/services/storage.service.js
- packages/front/svelte/views/association/association.service.js
- packages/front/svelte/views/home/Home.svelte
> 404 last search history

- packages/api/src/modules/providers/apiAsso/__fixtures__/ApiAssoDocumentFixture.ts
- packages/api/src/modules/providers/apiAsso/__fixtures__/ApiAssoStructureFixture.ts
- packages/api/src/modules/providers/apiAsso/__fixtures__/DtoDocumentFixture.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/adapters/__snapshots__/ApiAssoDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/modules/providers/apiAsso/dto/StructureDto.ts
- packages/api/src/shared/helpers/DateHelper.test.ts
- packages/api/src/shared/helpers/DateHelper.ts
- packages/front/svelte/components/CardDocuments.svelte
- packages/front/svelte/views/association/association.service.js
- packages/front/svelte/views/association/components/Documents.svelte
- packages/front/svelte/views/association/components/TabsAsso.svelte
> feat(api, front): find asso documents from API ASSO

- packages/front/.eslintrc
- packages/front/jest.config.js
- packages/front/jest.config.unit.js
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/example.test.js
> feat(front): init front unit tests

- packages/front/src/modules/etablissement/interfaces/http/EtablissementController.ts
- packages/front/svelte/helpers/dataHelper.js
- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/tsconfig.json
- packages/front/views/etablissement/components/etablissement/contacts.ejs
- packages/front/views/etablissement/components/etablissement/index.ejs
- packages/front/views/etablissement/index.ejs
> feat(front): add contacts csv download

- packages/api/src/modules/subventions/interfaces/http/SubventionController.ts
> docs(api): add docs on subvention controller

- packages/api/src/modules/search/interfaces/http/SearchController.ts
> docs(api): add docs on search controller

- packages/api/src/modules/user/repositories/user.repository.ts
> feat(api): use UserDbo in UserRepository collection type

- packages/api/src/modules/user/interfaces/http/ConsumerController.ts
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/user.service.ts
- packages/dto/consumer/ConsumerTokenDto.ts
- packages/dto/index.ts
> 513 create consumer controller

- packages/api/src/modules/stats/interfaces/http/StatsController.ts
> docs(api): add docs on stats controller

- packages/api/tools/betagouv/deploy-unite_legal.js
- packages/api/tools/betagouv/download_parser_unite_legal.sh
> feat(api): update script parsage datagouv

- packages/api/migrations/20221104145327-drop-entreprise-siren.js
> feat(api): drop collection entreprise siren

- packages/front/svelte/App.svelte
- packages/front/svelte/components/Matomo.svelte
- packages/front/views/footer.ejs
> feat(front): add management of user id to matomo

- packages/front/README.md
- packages/front/svelte/App.svelte
- packages/front/svelte/routes.js
- packages/front/svelte/services/router.service.js
- packages/front/svelte/shared/Router.svelte
- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/home/Home.svelte
> feat(front): enhance Router with dynamics routes

- packages/front/svelte/views/association/components/TabsAsso.svelte
> feat(front): align left tabs

- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/shared/Header.svelte
- packages/front/views/header.ejs
J'ai remarqué que le DSFR n'était pas à jour !
> chore(front): update DSFR and remove deprecated @types

- packages/front/src/modules/etablissement/interfaces/http/EtablissementController.ts
- packages/front/svelte/dsfr/Button.svelte
- packages/front/svelte/routes.js
- packages/front/svelte/services/router.service.js
- packages/front/svelte/shared/InfosLegales.svelte
- packages/front/svelte/shared/Router.svelte
- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/association/association.helper.js
- packages/front/svelte/views/association/association.helper.test.js
- packages/front/svelte/views/association/components/Documents.svelte
- packages/front/svelte/views/association/components/RnaSiren.svelte
- packages/front/svelte/views/association/components/dashboard/Dashboard.core.js
- packages/front/svelte/views/etablissement/Etablissement.svelte
- packages/front/svelte/views/etablissement/components/TabEtab.svelte
- packages/front/svelte/views/etablissement/etablissement.service.js
> feat(front): new etablissement page

- packages/front/src/modules/admin/interfaces/http/AdminController.ts
- packages/front/svelte/routes.js
- packages/front/svelte/views/admin/admin.service.js
- packages/front/svelte/views/admin/domains/AdminDomains.svelte
> feat(front): remplace ejs domain admin view in svelte view

- packages/api/src/configurations/auth.conf.ts
> feat(api): accept caissedesdepots.fr email domain

- packages/api/migrations/20221118092644-add-osiris-requests-indexes.js
> feat(api): add migration for osiris requests indexes

- packages/front/static/svelte-index.html
close #701 
source: https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icones
> feat(front): #701 include dsfr icons

- packages/front/svelte/shared/Footer.svelte
> 675 cgu svelte

- packages/api/src/modules/user/user.service.ts
@VSerain pour ton retour : problème détecté sur Postman avec `400 Bad Request : Request Header Or Cookie Too Large`
J'ai vu que le token retourné était très très long et diagnostiqué le problème potentiel : on sauvegarde le token à l'intérieur du JWT au moment du update (connexion < 2j). C'est inutile et fait grossir le token final pour rien. :)
Je t'ai ping pour te notifier puisque tu es en vacances que tu sache pourquoi c'est là
> fix(api): do not save user token within JWT on update

- packages/dto/package.json
the only relevant line :
`-  "main": "./build/index.js",`
https://github.com/indentjs/objectorarray/issues/7#issuecomment-864897781
> fix(dto): remove deprecate

- packages/front/src/modules/admin/interfaces/http/AdminController.ts
- packages/front/svelte/routes.js
- packages/front/svelte/services/router.service.js
- packages/front/svelte/views/admin/Admin.svelte
- packages/front/svelte/views/admin/stats/AdminStats.svelte
> feat(front): 656 base page for admin stats page

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.svelte
> fix(front): reduce asso's exercice filter size

- packages/front/svelte/services/router.service.js
> fix(front): display breadcrumb for Etablissement view

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.controller.js
> fix(front): display blank line for subvention with no versement

- packages/api/migrations/20221226095009-encode-api-rna-title.js
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/modules/providers/dataEntreprise/adapters/AssociationDtoAdapter.ts
Close #702
Faites pas attention au `from-de`au début j'étais parti de main et j'ai créé une autre branche plutôt que de me taper un merge de l'enfer
> 702 from dev special char truncated

- packages/front/svelte/resources/users/users.service.js
- packages/front/svelte/resources/users/users.service.test.js
> feat(front): add method is user actif

- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> feat(front): add user actif on admin view list

- packages/front/static/css/custom.css
- packages/front/svelte/global.css
- packages/front/svelte/views/admin/Admin.svelte
- packages/front/svelte/views/admin/users/AdminUsers.svelte
- packages/front/svelte/views/admin/users/composents/SearchUsers.svelte
> Interface Admin - Remaniement de la page listes utilisateurs et changements des libellées

- CHANGELOG.md
- packages/api/README.md
- packages/front/README.md
> feat(api, front): update README

- packages/front/svelte/global.css
- packages/front/svelte/views/association/components/Etablissements.svelte
- packages/front/svelte/views/etablissement/etablissement.service.js
> feat(front): update asso etab card

- packages/front/nodemon.json
- packages/front/svelte/App.svelte
- packages/front/svelte/components/FullPageSpinner.svelte
- packages/front/svelte/components/Router.svelte
- packages/front/svelte/global.css
- packages/front/svelte/store/context.store.js
- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/etablissement/Etablissement.svelte
> feat(front): add blue banner for asso and etab view

- packages/front/svelte/views/association/components/Etablissements.svelte
> feat(front): open etab view in current tab

- packages/front/svelte/components/CardDocuments.svelte
> feat(front): force document download in a new tab

- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> test(api): add many test on find documents in api asso provider

- packages/api/src/modules/stats/interfaces/http/StatsController.test.ts
- packages/api/src/modules/stats/interfaces/http/StatsController.ts
- packages/api/src/modules/stats/repositories/statsRepository.test.ts
- packages/api/src/modules/stats/repositories/statsRepository.ts
- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/src/modules/user/repositories/user.repository.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/shared/helpers/DateHelper.test.ts
- packages/api/src/shared/helpers/DateHelper.ts
- packages/api/tests/modules/stats/stats.spec.ts
- packages/api/tests/modules/user/__fixtures__/entity.ts
> feat(api): #737 cumulative nb users by month one year

- packages/api/src/modules/stats/repositories/__snapshots__/stats.repository.test.ts.snap
- packages/api/src/modules/stats/repositories/stats.repository.ts
> fix(api): keep just good request

- packages/api/README.md
- packages/front/README.md
> feat(api, front): add code convention to README

- packages/front/package-lock.json
- packages/front/svelte/dsfr/Select.svelte
- packages/front/svelte/helpers/dateHelper.js
- packages/front/svelte/helpers/dateHelper.test.js
- packages/front/svelte/resources/stats/stats.port.js
- packages/front/svelte/resources/stats/stats.port.test.js
- packages/front/svelte/resources/stats/stats.service.js
- packages/front/svelte/resources/stats/stats.service.test.js
- packages/front/svelte/resources/versements/versements.port.js
- packages/front/svelte/views/admin/users/AdminUsersMetrics.svelte
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.js
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.svelte
> feat(front): #661 widget user nb

- packages/api/src/modules/providers/apiAsso/__fixtures__/ApiAssoDocumentFixture.ts
- packages/api/src/modules/providers/apiAsso/__fixtures__/ApiAssoStructureFixture.ts
- packages/api/src/modules/providers/apiAsso/__fixtures__/DtoDocumentFixture.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/adapters/__snapshots__/ApiAssoDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/modules/providers/apiAsso/dto/StructureDto.ts
> feat(api): change management of api asso files

- packages/api/src/modules/stats/interfaces/http/StatsController.test.ts
- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/tests/modules/stats/stats.spec.ts
- packages/front/package-lock.json
- packages/front/svelte/resources/stats/stats.service.js
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.js
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
> 862 add user before year

- packages/front/src/modules/auth/AuthService.ts
- packages/front/src/modules/auth/interfaces/http/AuthController.ts
- packages/front/svelte/components/Auth.svelte
- packages/front/svelte/dsfr/Button.svelte
- packages/front/svelte/dsfr/Input.svelte
- packages/front/svelte/resources/auth/auth.port.js
- packages/front/svelte/resources/auth/auth.port.test.js
- packages/front/svelte/resources/auth/auth.service.js
- packages/front/svelte/resources/auth/auth.service.test.js
- packages/front/svelte/routes.js
- packages/front/svelte/services/router.service.js
- packages/front/svelte/views/auth/signup/Signup.controller.js
- packages/front/svelte/views/auth/signup/Signup.controller.test.js
- packages/front/svelte/views/auth/signup/Signup.svelte
closes #891 
J'ai modifié un peu `Button` et `Input` mais sans reprendre leur parce que j'ai considéré que ce n'était pas le scope de la PR, et pour `Input` le composant et déjà très simple
> feat(front): #891 signup page svelte

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.svelte
> chore(front): 825 spelling

- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/front/svelte/resources/stats/stats.port.js
- packages/front/svelte/resources/stats/stats.service.js
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.js
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
closes #908 
Il restera le tooltip à faire pour clore ce widget (#900)
> feat(front,api): 908 fix monthly user count data format

- packages/api/src/modules/stats/interfaces/http/StatsController.test.ts
- packages/api/src/modules/stats/interfaces/http/StatsController.ts
- packages/api/src/modules/stats/repositories/stats.repository.test.ts
- packages/api/src/modules/stats/repositories/stats.repository.ts
- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/src/shared/helpers/DateHelper.test.ts
- packages/api/src/shared/helpers/DateHelper.ts
- packages/dto/stats/MonthlyAvgRequestDtoResponse.ts
- packages/dto/stats/MonthlyRequestsDtoResponse.ts
- packages/dto/stats/index.ts
> 935 api format nb requests

- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/association/components/Stats/Stats.svelte
- packages/front/svelte/views/association/components/TabsAsso.svelte
> feat(front): add stats page on association

- packages/front/svelte/views/auth/signup/Signup.svelte
> feat(api): wording agents publics

- packages/front/svelte/components/Stats/MonthlyGraph/MonthlyGraph.controller.js
- packages/front/svelte/components/Stats/MonthlyGraph/MonthlyGraph.controller.test.js
- packages/front/svelte/components/Stats/MonthlyGraph/MonthlyGraph.svelte
- packages/front/svelte/components/Stats/MonthlyGraphTooltip/MonthlyGraphTooltip.controller.js
- packages/front/svelte/components/Stats/MonthlyGraphTooltip/MonthlyGraphTooltip.controller.test.js
- packages/front/svelte/components/Stats/MonthlyGraphTooltip/MonthlyGraphTooltip.svelte
- packages/front/svelte/views/admin/stats/components/MonthlyRequestCountByYear/MonthlyRequestCountByYear.svelte
- packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.svelte
> 900 tooltip chart

- packages/api/src/modules/providers/apiEntreprise/apiEntreprise.service.test.ts
- packages/api/src/modules/providers/apiEntreprise/apiEntreprise.service.ts
> fix(api): remove .only in tests and fix etablissement headcount url

- packages/api/src/modules/etablissements/etablissements.service.test.ts
- packages/api/src/modules/etablissements/etablissements.service.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.test.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.ts
- packages/api/tests/modules/etablissements/etablissements.spec.ts
> refactor(api): move error handling in service

- packages/api/src/cli.ts
- packages/api/src/configurations/apis.conf.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.ts
- packages/api/src/modules/providers/demarchesSimplifiees/interfaces/cli/demarchesSimplifiees.cli.controller.ts
- packages/api/src/modules/providers/index.ts
- packages/api/tests/modules/open-data/providers/__snapshots__/providers.spec.ts.snap
closes #967 
Je ne sais pas si ça couvre le ticket, j'ai grosso modo converti la route qu'on avait sur postman.
> 967 demarches simpl poc

- packages/api/migrations/20230217083147-add-index-stats-associations-visits.js
- packages/api/package-lock.json
- packages/api/src/modules/stats/entities/UserWithAssociationVisitsEntity.ts
- packages/api/src/modules/stats/interfaces/http/StatsController.ts
- packages/api/src/modules/stats/joiners/UserAssociationVisitsJoiner.ts
- packages/api/src/modules/stats/repositories/statsAssociationsVisit.repository.ts
- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/src/modules/user/repositories/user.repository.ts
- packages/api/src/shared/helpers/DateHelper.test.ts
- packages/api/src/shared/helpers/DateHelper.ts
> feat(api): add endpoint user by request

- packages/api/jest.config.integ.env.ts
- packages/api/tests/modules/associations/associations.spec.ts
- packages/api/tests/modules/etablissements/etablissements.spec.ts
> refactor(api): mock axios for all integration tests

- CHANGELOG.md
- lerna.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/resources/auth/auth.service.js
closes #1023 
~~J'ai fait la PR vers develop parce que si je la fait vers PROD ça embarque des commits doublons :grimacing: donc à régler en parallèle~~
~~C'est parce que je l'ai faite depuis dev, je corrige~~
C'est bon
> hotfix(front): redirect to home on 404 only if route needs auth

- packages/api/src/modules/etablissements/etablissements.service.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/front/src/index.ts
- packages/front/svelte/components/Router/Router.controller.js
- packages/front/svelte/resources/auth/auth.service.js
Close #892 
PS: je dois d'abord rebase avec la page 404 pour que ça fonctionne (tourne en boucle en l'état)
> feat(front): redirect all calls to svelte

- packages/api/src/modules/associations/interfaces/http/AssociationController.test.ts
- packages/api/src/modules/associations/interfaces/http/AssociationController.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.test.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.ts
closes #1013 
il me semble que c'était tout, ensuite pour lire les utilisateurs c'est #1014 qui va trier les logs, si mon souvenir est bon
> 1013 register extracts

- packages/api/src/cli.ts
- packages/api/src/modules/providers/caisseDepots/adapters/__snapshots__/caisseDepotsDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/caisseDepots/adapters/caisseDepotsDtoAdapter.test.ts
- packages/api/src/modules/providers/caisseDepots/adapters/caisseDepotsDtoAdapter.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.cli.controller.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.test.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.ts
- packages/api/src/modules/providers/caisseDepots/dto/CaisseDepotsSubvDto.ts
- packages/api/src/modules/providers/caisseDepots/dto/CaisseDepotsSubventionDto.ts
- packages/api/src/modules/providers/dauphin/dto/DauphinSubventionDto.ts
- packages/api/src/modules/providers/index.ts
- packages/api/src/modules/providers/osiris/adapters/OsirisRequestAdapter.test.ts
- packages/api/src/shared/helpers/DateHelper.test.ts
- packages/api/src/shared/helpers/DateHelper.ts
- packages/api/tests/modules/open-data/providers/__snapshots__/providers.spec.ts.snap
- packages/api/tests/modules/providers/caisseDepots/entity.ts
- packages/dto/search/DemandeSubvention.ts
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersemementsStatistique/SubventionsVersemementsStatistique.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersemementsStatistique/SubventionsVersemementsStatistique.svelte
closes #945 
à check avec Yasmine
- montant
- date début/fin 
- commission
- année demandée
- service instructeur (wording)
- dispositif <-> objet
- quel nom on affiche 
- texte présentation provider
> 945 caisse depots

- packages/api/src/modules/stats/interfaces/http/StatsController.test.ts
- packages/api/src/modules/stats/interfaces/http/StatsController.ts
- packages/api/src/modules/stats/repositories/stats.repository.ts
- packages/api/src/modules/stats/stats.service.test.ts
- packages/api/src/modules/stats/stats.service.ts
> 1014 see extractors emails

- packages/front/jest.config.js
- packages/front/svelte/resources/auth/auth.service.js
- packages/front/svelte/resources/auth/auth.service.test.js
- packages/front/svelte/services/crisp.service.js
- packages/front/svelte/services/crisp.service.test.js
> 1001 crisp email

- CHANGELOG.md
- lerna.json
- packages/api/CHANGELOG.md
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
- packages/api/src/modules/providers/dauphin/dto/DauphinSubventionDto.ts
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
Fix ce souci : 
L'erreur survient quand on load cette asso : http://localhost:1235/association/W313003420
> fix(api): add more check on use dauphin data

- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
Fix plusieurs erreurs que j'ai vu dans les logs de la production ! 
Ce sont des erreurs qui ne font pas tomber le service, donc pas en hotfix !
Elles sont toute liée à l'api asso
> Fix many error on prod

- packages/api/src/modules/open-data/rna-siren/interfaces/http/RnaSirenController.ts
- packages/api/src/modules/open-data/rna-siren/rnaSiren.service.test.ts
- packages/api/src/modules/open-data/rna-siren/rnaSiren.service.ts
> 768 rnaSiren error middleware

- packages/front/svelte/resources/auth/auth.service.js
- packages/front/svelte/resources/auth/auth.service.test.js
- packages/front/svelte/services/crisp.service.js
- packages/front/svelte/services/crisp.service.test.js
> 1058 fix crisp

- packages/api/src/modules/providers/caisseDepots/adapters/__snapshots__/caisseDepotsDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/caisseDepots/adapters/caisseDepotsDtoAdapter.ts
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.test.ts
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
- packages/api/src/modules/providers/fonjep/adapters/FonjepEntityAdapter.ts
- packages/api/src/modules/providers/fonjep/adapters/__snapshots__/FonjepEntityAdapter.test.ts.snap
- packages/api/src/modules/providers/gispro/adapters/GisproRequestAdapter.ts
- packages/api/src/modules/providers/helper.test.ts
- packages/api/src/modules/providers/helper.ts
- packages/api/src/modules/providers/osiris/adapters/OsirisRequestAdapter.test.ts
- packages/api/src/modules/providers/osiris/adapters/OsirisRequestAdapter.ts
- packages/api/src/modules/providers/osiris/adapters/__snapshots__/OsirisRequestAdapter.test.ts.snap
- packages/api/tests/modules/associations/__snapshots__/associations.spec.ts.snap
- packages/api/tests/modules/associations/associations.spec.ts
- packages/api/tests/modules/providers/gispro/adapter/GisproRequestAdapter.test.ts
- packages/dto/search/DemandeSubvention.ts
> 1045 homogenize status

- packages/front/jest.config.unit.env.js
- packages/front/jest.config.unit.js
- packages/front/svelte/components/StructureTitle/StructureTitle.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.test.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/__snapshots__/SubventionTable.controller.test.js.snap
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.test.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.controller.test.js
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/__snapshots__/VersementTable.controller.test.js.snap
- packages/front/svelte/helpers/csvHelper.js
- packages/front/svelte/resources/associations/association.port.js
- packages/front/svelte/resources/associations/association.port.test.js
- packages/front/svelte/resources/associations/association.service.js
- packages/front/svelte/resources/associations/association.service.test.js
- packages/front/svelte/resources/establishments/establishment.port.js
- packages/front/svelte/resources/establishments/establishment.port.test.js
- packages/front/svelte/resources/establishments/establishment.service.js
- packages/front/svelte/resources/establishments/establishment.service.test.js
> 1012 dl datasub array

- packages/api/src/modules/user/interfaces/http/ConsumerController.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/__helpers__/getAdminToken.ts
- packages/api/tests/__helpers__/getUserToken.ts
- packages/api/tests/__helpers__/tokenHelper.ts
- packages/api/tests/modules/associations/associations.spec.ts
- packages/api/tests/modules/configurations/configurations.spec.ts
- packages/api/tests/modules/etablissements/etablissements.spec.ts
- packages/api/tests/modules/open-data/rna-siren/interfaces/http/RnaSirenController.test.ts
- packages/api/tests/modules/search/search.spec.ts
- packages/api/tests/modules/stats/stats.spec.ts
- packages/api/tests/modules/user/consumer.spec.ts
- packages/api/tests/modules/user/user.spec.ts
> 1065 consumer controller error handling

- packages/api/src/modules/search/interfaces/http/SearchController.ts
- packages/api/src/modules/search/search.service.ts
- packages/api/tests/modules/search/search.spec.ts
> Search controller error handling

- packages/front/svelte/views/admin/users/AdminUsersAccount.svelte
> 1073 list user sort

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.test.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.svelte
- packages/front/svelte/components/Tables/TableCell.svelte
- packages/front/svelte/components/Tables/TableHead.svelte
- packages/front/svelte/dsfr/Table.svelte
- packages/front/svelte/global.css
> 1046 subvention clickable row to have more info

- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.ts
- packages/api/tests/modules/providers/chorus/chorus.service.test.ts
- packages/dto/versements/VersementChorus.ts
> 1018 chorus bop

- CHANGELOG.md
- lerna.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/components/Footer.svelte
> HOTFIX : 1140 stats footer

- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.controller.test.js
- packages/front/svelte/resources/versements/versements.adapter.js
- packages/front/svelte/resources/versements/versements.adapter.test.js
> refactor(front): create VersementsAdapter to manage versement display

- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
> fix(api): change provider name of rib documents

- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> fix(api): delete consumer if could not create token

- packages/front/package-lock.json
- packages/front/svelte/errors/errors.service.js
- packages/front/svelte/errors/index.js
- packages/front/svelte/resources/auth/auth.port.js
- packages/front/svelte/resources/auth/auth.port.test.js
- packages/front/svelte/resources/auth/auth.service.js
- packages/front/svelte/resources/versements/versements.port.js
- packages/front/svelte/resources/versements/versements.port.test.js
- packages/front/svelte/services/requests.service.js
- packages/front/svelte/services/requests.service.test.js
> 550 request service

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.svelte
> feat(front): hide exercice filter

- packages/front/svelte/resources/versements/versements.adapter.js
- packages/front/svelte/resources/versements/versements.adapter.test.js
> fix(front): display hyphen in total amount when no versements

- packages/api/src/cron.ts
- packages/api/src/decorators/cronController.decorator.ts
- packages/api/src/modules/example/interfaces/cron/demarchesSimplifiees.cron.controller.test.ts
- packages/api/src/modules/example/interfaces/cron/demarchesSimplifiees.cron.controller.ts
closes #1165 
requires #1164 :heavy_check_mark:
> 1165 cron demarches simpl

- packages/api/migrations/20230406132749-creates-index-dauphin.js
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/dauphin/repositories/dauphin-gispro.repository.ts
- packages/api/src/modules/providers/dauphin/repositories/dbo/DauphinGisproDbo.ts
- packages/api/src/modules/providers/gispro/interfaces/cli/gispro.cli.controller.ts
> 1079 insert gispro data in database

- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
> feat(api): add ej and versementkey on dauphin dto

- packages/api/src/modules/user/user.service.ts
> feat(api): user not found in login should be 401

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/__snapshots__/SubventionTable.controller.test.js.snap
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.svelte
- packages/front/svelte/components/Tables/TableHead.svelte
- packages/front/svelte/resources/subventions/subventions.adapter.js
- packages/front/svelte/resources/subventions/subventions.adapter.test.js
Close #1143 
Version 2 pour éviter le rebase lourd sur develop
> feat(front): add establishment siret to application table

- packages/api/src/modules/providers/dauphin/__snapshots__/dauphin.service.test.ts.snap
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/dauphin/interfaces/cli/dauphin.cli.controller.ts
Close #683 
PR refaite pour éviter les duplication de commit après nombreux rebases
> 683 fetch and save dauphin data 2

- packages/api/src/modules/providers/demarchesSimplifiees/interfaces/cli/demarchesSimplifiees.cli.controller.ts
> chore(api): spelling cli demarches simplifiees

- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> chore(api): remove unused method

- packages/dto/grant/grant.ts
> feat(dto): common grant dto

- packages/api/src/modules/etablissements/etablissements.service.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
closes #1221 
J'ai aussi créé le ticket #1239 parce que je pense qu'à trop catch des erreurs sans faire de suivi on augmente notre niveau de machine à gaz
> 1221 catch provider errors

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.svelte
> feat(front): wording no data in table

- packages/front/svelte/components/Router/Router.controller.js
- packages/front/svelte/components/Router/Router.controller.test.js
- packages/front/svelte/errors/UnauthorizedError.js
- packages/front/svelte/errors/errors.service.js
- packages/front/svelte/errors/index.js
- packages/front/svelte/resources/auth/auth.service.js
- packages/front/svelte/views/auth/login/Login.controller.js
- packages/front/svelte/views/auth/login/Login.controller.test.js
> 1110 redirect after login

- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsStatistique/SubventionsVersementsStatistique.svelte
> feat(front): hide subv percentage (potentially inaccurate)

- packages/front/svelte/components/Stats/MonthlyGraphTooltip/MonthlyGraphTooltip.controller.js
- packages/front/svelte/components/Stats/MonthlyGraphTooltip/MonthlyGraphTooltip.controller.test.js
- packages/front/svelte/components/SubventionsVersementsDashboard/Modals/SubventionInfoModal.svelte
- packages/front/svelte/helpers/stringHelper.js
- packages/front/svelte/helpers/stringHelper.test.js
- packages/front/svelte/helpers/textHelper.js
- packages/front/svelte/resources/subventions/subventions.adapter.js
- packages/front/svelte/resources/subventions/subventions.adapter.test.js
- packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> 1117 merge string helper

- packages/api/src/cron.ts
- packages/api/src/modules/providers/dauphin/__snapshots__/dauphin.service.test.ts.snap
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/dauphin/interfaces/cli/dauphin.cli.controller.ts
- packages/api/src/modules/providers/dauphin/interfaces/cron/dauphin.cron.controller.ts
- packages/api/src/modules/providers/dauphin/repositories/dauphin-gispro.repository.ts
- packages/api/tests/modules/providers/dauphin-gispro/dauphin-gispro.repository.spec.ts
Close #685 
J'ai mis 20h mais on peut se mettre d'accord sur une heure plus adaptée ? Milieu de la nuit ou 5h comme pour DS ?
> 685 dauphin cron

- packages/api/src/modules/documents/@types/DocumentsProvider.ts
- packages/api/src/modules/documents/documents.service.test.ts
- packages/api/src/modules/documents/documents.service.ts
- packages/api/src/modules/etablissements/etablissements.service.test.ts
- packages/api/src/modules/etablissements/etablissements.service.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.test.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/modules/providers/apiAsso/dto/StructureDto.ts
> feat(api): add establishment document rib route

- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.test.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.subvention.repository.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.versement.repository.ts
- packages/api/tools/fonjep/drop-and-import-file.js
> feat(api): add database management

- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.test.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.subvention.repository.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.versement.repository.ts
- packages/api/tools/fonjep/drop-and-import-file.js
Reverts betagouv/api-subventions-asso#1272
> Revert "feat(api): add database management"

- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/modules/providers/bodacc/adapters/__snapshots__/bodacc.adapter.test.ts.snap
- packages/api/src/modules/providers/bodacc/adapters/bodacc.adapter.ts
- packages/api/src/modules/providers/bodacc/dto/BodaccDto.ts
- packages/dto/associations/Association.ts
- packages/dto/associations/BodaccRecordDto.ts
- packages/dto/package-lock.json
- packages/dto/package.json
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/dsfr/Callout.svelte
- packages/front/svelte/global.css
- packages/front/svelte/helpers/providerValueHelper.js
- packages/front/svelte/helpers/providerValueHelper.test.js
- packages/front/svelte/resources/associations/association.service.js
- packages/front/svelte/resources/associations/association.service.test.js
- packages/front/svelte/views/association/Association.svelte
- packages/front/svelte/views/association/components/Bodacc/Announcement.controller.js
- packages/front/svelte/views/association/components/Bodacc/Announcement.controller.test.js
- packages/front/svelte/views/association/components/Bodacc/Announcement.svelte
- packages/front/svelte/views/association/components/Bodacc/Bodacc.controller.js
- packages/front/svelte/views/association/components/Bodacc/Bodacc.svelte
- packages/front/svelte/views/association/components/Bodacc/__snapshots__/Announcement.controller.test.js.snap
- packages/front/svelte/views/association/components/TabsAsso.svelte
> feat(front, api, dto): add boddac tab

- packages/api/migrations/20230418074728-dauphin-caches-to-dauphin-gispro.js
> feat(api): add migration dauphin to dauphin gispro

- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.test.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.core.repository.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.subvention.repository.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.versement.repository.ts
- packages/api/tests/modules/providers/fonjep/__snapshots__/fonjep.spec.ts.snap
- packages/api/tests/modules/providers/fonjep/fonjep.spec.ts
- packages/api/tools/fonjep/drop-and-import-file.js
> Coup de propre sur l'import de données fonjep

- .gitignore
- packages/api/.eslintrc.yaml
- packages/api/package-lock.json
- packages/api/src/modules/providers/gispro/interfaces/cli/gispro.cli.controller.ts
- packages/api/tools/.gitignore
- packages/dto/.eslintrc.yaml
- packages/front/.eslintrc.yaml
- packages/front/package-lock.json
- packages/front/svelte/components/Router/Router.controller.test.js
- packages/front/svelte/components/SubventionsVersementsDashboard/SubventionsVersementsStatistique/SubventionsVersementsStatistique.svelte
- packages/front/svelte/resources/auth/auth.port.test.js
- packages/front/svelte/resources/versements/versements.adapter.test.js
- packages/tools/.eslintrc.yaml
- packages/tools/osiris-automation/Osiris/OsirisExtractDownloader.js
- packages/tools/osiris-automation/Osiris/OsirisPosibilitiesBuilder.js
- packages/tools/osiris-automation/Osiris/OsirisSignalrConnector.js
- packages/tools/osiris-automation/Osiris/jQueryNodeLoader.js
- packages/tools/osiris-automation/OsirisPuppeteer/OsirisPuppeteer.js
- packages/tools/osiris-automation/OsirisPuppeteer/browser-script.js
- packages/tools/osiris-automation/cleaned_modules/signalR/jquery.signalR.js
- packages/tools/osiris-automation/index.js
- packages/tools/package-lock.json
- packages/tools/package.json
> chore(tools): add osiris data extractor

- package.json
pb : https://stackoverflow.com/a/60335168/14872075
> fix: run lerna lint sequentially to not loose work

- packages/api/src/modules/providers/bodacc/dto/BodaccDto.ts
> feat(api): remove links from BodaccDto

- packages/api/src/modules/stats/joiners/UserAssociationVisitsJoiner.ts
closes #1300 mais c'est bcp trop lents avec les services
> fix(api): fix mongodb request

- packages/api/src/modules/associations/associations.service.ts
- packages/api/src/modules/associations/interfaces/http/AssociationController.test.ts
- packages/api/src/modules/associations/interfaces/http/AssociationController.ts
- packages/api/src/modules/grant/@types/GrantProvider.ts
- packages/api/src/modules/grant/@types/rawGrant.ts
- packages/api/src/modules/grant/__snapshots__/grant.service.test.ts.snap
- packages/api/src/modules/grant/grant.service.test.ts
- packages/api/src/modules/grant/grant.service.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.test.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.ts
- packages/api/src/modules/providers/chorus/chorus.service.test.ts
- packages/api/src/modules/providers/chorus/chorus.service.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
- packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
- packages/api/src/modules/providers/fonjep/joiners/fonjepJoiner.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.subvention.repository.ts
- packages/api/src/modules/providers/fonjep/repositories/fonjep.versement.repository.ts
- packages/api/src/modules/providers/osiris/osiris.service.test.ts
- packages/api/src/modules/providers/osiris/osiris.service.ts
- packages/api/tests/modules/open-data/providers/__snapshots__/providers.spec.ts.snap
- packages/dto/index.ts
closes #1294 
pas fini mais tu peux relire l'esprit si tu veux. Il manque les tests et à finir le tour des providers. J'aurais pu faire des tickets différents mais je n'avais pas le cœur à en créer autant
> 1294 grant service

- packages/api/migrations/20230418074728-dauphin-caches-to-dauphin-gispro.js
- packages/api/migrations/20230525120112-create-unique-association-visit-collection.js
- packages/api/src/modules/stats/repositories/__fixtures__/VisitsGroupByAssociationIdentifier.json
- packages/api/src/modules/stats/repositories/__snapshots__/statsUniqueVisitByDay.repository.test.ts.snap
- packages/api/src/modules/stats/repositories/statsAssociationsVisit.repository.ts
- packages/api/src/modules/stats/repositories/statsUniqueVisitByDay.repository.test.ts
- packages/api/src/modules/stats/repositories/statsUniqueVisitByDay.repository.ts
> 1358 create group by day association visit

- CHANGELOG.md
- lerna.json
- packages/api/CHANGELOG.md
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/modules/providers/dauphin/__snapshots__/dauphin.service.test.ts.snap
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/dto/CHANGELOG.md
- packages/dto/package-lock.json
- packages/dto/package.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/tools/CHANGELOG.md
- packages/tools/package-lock.json
- packages/tools/package.json
> Hotfix dauphin

- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/shared/errors/LoginError.ts
> feat(api, dto): update login error message

- packages/api/src/modules/grant/commonGrant.service.test.ts
- packages/api/src/modules/grant/commonGrant.service.ts
- packages/api/src/modules/grant/grant.service.test.ts
- packages/api/src/modules/grant/grant.service.ts
- packages/api/src/modules/providers/@types/IProvider.ts
closes #1325
angle mort métier sur `chooseApplication`
> 1325 common grant

- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.test.ts
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
- packages/api/src/modules/providers/dauphin/adapters/__snapshots__/DauphinDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/dauphin/repositories/dbo/DauphinGisproDbo.ts
> 1192 dauphin common adapter

- packages/api/src/modules/providers/osiris/adapters/OsirisRequestAdapter.test.ts
- packages/api/src/modules/providers/osiris/adapters/OsirisRequestAdapter.ts
- packages/api/src/modules/providers/osiris/adapters/__snapshots__/OsirisRequestAdapter.test.ts.snap
- packages/api/src/modules/providers/osiris/osiris.service.test.ts
- packages/api/src/modules/providers/osiris/osiris.service.ts
> 1297 osiris common adapter

- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.test.ts
- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.ts
- packages/api/src/modules/providers/chorus/adapters/__snapshots__/ChorusAdapter.test.ts.snap
- packages/api/src/modules/providers/chorus/chorus.service.test.ts
- packages/api/src/modules/providers/chorus/chorus.service.ts
> 1296 chorus adapter

- packages/api/src/modules/open-data/grant/interfaces/http/GrantController.ts
- packages/api/src/modules/open-data/grant/openDataGrantService.ts
closes #1360 
à merge après #1387
> 1360 open data routes

- packages/api/.eslintrc.yaml
- packages/api/src/modules/providers/caisseDepots/adapters/__snapshots__/caisseDepotsDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/caisseDepots/adapters/caisseDepotsDtoAdapter.test.ts
- packages/api/src/modules/providers/caisseDepots/adapters/caisseDepotsDtoAdapter.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.test.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.ts
- packages/dto/.eslintrc.yaml
- packages/front/.eslintrc.yaml
- packages/tools/.eslintrc.yaml
> 1191 caisse depots adapter

- packages/api/src/modules/grant/grant.service.ts
- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.ts
- packages/api/src/modules/providers/chorus/adapters/__snapshots__/ChorusAdapter.test.ts.snap
- packages/api/src/modules/providers/demarchesSimplifiees/adapters/DemarchesSimplifieesEntityAdapter.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/adapters/DemarchesSimplifieesEntityAdapter.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.ts
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-62744-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-62746-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-62747-form.json
- packages/dto/grant/grant.ts
> 1194 demarches simplifiees common adapter

- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/decorators/cronController.decorator.ts
- packages/api/src/modules/associations/associations.service.ts
- packages/api/src/modules/documents/documents.service.ts
- packages/api/src/modules/etablissements/etablissements.service.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/modules/providers/caisseDepots/caisseDepots.service.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.ts
- packages/api/src/server.ts
closes #1239 
voir https://sentry.incubateur.net/organizations/betagouv/projects/data-subvention-api/?project=96
> 1239 sentry

- packages/front/svelte/components/SubventionsVersementsDashboard/Modals/VersementsInfoModal.svelte
- packages/front/svelte/components/SubventionsVersementsDashboard/VersementTable/VersementTable.controller.js
- packages/front/svelte/resources/versements/versements.adapter.js
- packages/front/svelte/resources/versements/versements.adapter.test.js
> 1302 multi bop

- packages/front/svelte/components/EstablishmentPreview/EstablishmentPreview.svelte
- packages/front/svelte/components/EstablishmentPreview/EstablishmentPreviewController.js
- packages/front/svelte/dsfr/Badge.svelte
- packages/front/svelte/dsfr/BadgeGroup.svelte
- packages/front/svelte/dsfr/Card.svelte
- packages/front/svelte/resources/associations/association.service.js
- packages/front/svelte/views/association/components/EstablishmentCard.controller.js
- packages/front/svelte/views/association/components/EstablishmentCard.svelte
- packages/front/svelte/views/association/components/Etablissements.svelte
- packages/front/svelte/views/etablissement/Etablissement.svelte
> 1376 establishment card

- packages/front/src/index.ts
> feat(front): redirect stats to blog stats page

- packages/front/svelte/views/etablissement/components/TabsEtab.svelte
> fix(front): use english variable name

- packages/api/src/modules/user/repositories/consumer-token.repository.ts
- packages/api/src/modules/user/repositories/user-reset.repository.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> 1428 fuller user delete

- packages/api/src/modules/providers/datagouv/@types/DataGouvExtractDbo.ts
- packages/api/src/modules/providers/datagouv/@types/ScdlEtalabDbo.ts
- packages/api/src/modules/providers/datagouv/@types/ScdlGrantDbo.ts
> 1364 storage conception

- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.test.ts
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
- packages/api/src/modules/providers/dauphin/dto/DauphinDocumentDto.ts
closes #1429
closes #1430
closes #1431
closes #1432
closes #1444
> Sentry fixes

- packages/api/src/modules/stats/repositories/stats.repository.ts
- packages/api/src/modules/stats/repositories/statsAssociationsVisit.repository.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/repositories/consumer-token.repository.ts
- packages/api/src/modules/user/repositories/user-reset.repository.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/shared/WithStringId.ts
- packages/api/src/shared/helpers/RepositoryHelper.test.ts
- packages/api/src/shared/helpers/RepositoryHelper.ts
- packages/dto/user/UserDataDto.ts
- packages/dto/user/index.ts
> feat(api): add endpoint for getting all user data

- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/modules/user/user.service.test.ts
> 1478 update brevo contact on activation

- packages/api/jest.config.integ.env.ts
- packages/api/jest.config.unit.env.ts
- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> feat(api): update user last connection date in brevo after login

- packages/front/svelte/components/Router/Router.controller.js
- packages/front/svelte/components/Router/Router.controller.test.js
- packages/front/svelte/resources/auth/auth.port.js
- packages/front/svelte/resources/auth/auth.port.test.js
- packages/front/svelte/resources/auth/auth.service.js
- packages/front/svelte/resources/auth/auth.service.test.js
- packages/front/svelte/views/auth/login/Login.svelte
- packages/front/svelte/views/auth/signup/Signup.controller.js
- packages/front/svelte/views/auth/signup/Signup.controller.test.js
- packages/front/svelte/views/auth/signup/Signup.svelte
> 1306 new signup page

- packages/front/svelte/dsfr/Button.svelte
- packages/front/svelte/dsfr/ModalFooter.svelte
- packages/front/svelte/store/modal.store.js
- packages/front/svelte/views/user/profile/components/ConfirmDeleteUserModal.svelte
- packages/front/svelte/views/user/profile/components/DeleteUser.svelte
> feat(front): add modal on user deleted action

- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/user/interfaces/http/AuthentificationController.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/modules/user/authentification.spec.ts
- packages/api/tests/modules/user/user.service.test.ts
- packages/front/svelte/views/auth/forget-pwd/ForgetPwd.svelte
> refactor: security dont say if user exit in forget password

- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/modules/user/user.service.test.ts
- packages/front/svelte/views/auth/signup/Signup.controller.js
> refactor: security dont say if user exit in signup

- packages/api/src/authentication/express.auth.hooks.ts
- packages/api/src/modules/user/interfaces/cli/consumer.cli.controller.ts
- packages/api/src/modules/user/interfaces/http/AuthentificationController.ts
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> refactor(api): tolowercase on interfaces not in service

- packages/front/svelte/views/auth/signup/Signup.controller.js
- packages/front/svelte/views/auth/signup/Signup.svelte
closes #1502 
J'ai hésité à mettre le lien en variable d'env, mais comme c'est un lien interne je l'ai pas fait
> 1502 cgu signup

- packages/front/svelte/resources/associations/association.port.js
- packages/front/svelte/resources/associations/association.port.test.js
> refactor(front): use request service in association port

- packages/front/svelte/views/auth/login/Login.controller.js
- packages/front/svelte/views/auth/login/Login.controller.test.js
- packages/front/svelte/views/auth/login/Login.svelte
- packages/front/svelte/views/auth/signup/Signup.svelte
Close #1503 
PS: je suis planté dans le numéro de la branche mais c'est bien la 1503
> new login page

- packages/front/jest.config.js
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/dsfr/Input.svelte
- packages/front/svelte/dsfr/Select.svelte
> 872 form inputs unique

- packages/front/svelte/resources/auth/auth.port.js
- packages/front/svelte/resources/auth/auth.port.test.js
- packages/front/svelte/resources/auth/auth.service.test.js
- packages/front/svelte/resources/documents/documents.port.js
- packages/front/svelte/resources/documents/documents.port.test.js
- packages/front/svelte/resources/providers/providers.port.js
- packages/front/svelte/resources/providers/providers.port.test.js
- packages/front/svelte/resources/stats/stats.port.js
- packages/front/svelte/resources/stats/stats.port.test.js
- packages/front/svelte/resources/subventions/subventions.port.js
- packages/front/svelte/resources/versements/versements.port.test.js
closes #1178 
closes #1177 
closes #1179
also documentPort, authPort and authService use requestService instead of direct axios
> Request service

- packages/front/svelte/views/auth/login/Login.svelte
finalise la page de login (affichage du mot de passe au clic) mais qui diffère du design de Marion pour des raisons de faisabilité / comptabilité avec le DSFR (accessibilité etc)
> feat(front): add checkbox to display password

- CHANGELOG.md
- lerna.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/svelte/views/association/components/Bodacc/Announcement.controller.js
Fix le soucis sur la prod !
Ticket créer pour plus approfondir: https://github.com/betagouv/api-subventions-asso/issues/1533
> Hotfix bodacc judgmentobj

- CHANGELOG.md
- lerna.json
- packages/api/CHANGELOG.md
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/middlewares/DocsMiddleware.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.service.ts
> fix(api): open-data show all fonjep even if same EJ

- packages/api/package-lock.json
- packages/api/src/modules/_open-data/grant/interfaces/http/GrantController.ts
- packages/dto/grant/grant.ts
> fix(dto): fix swagger doc on open data

- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/user/interfaces/cli/user.cli.controller.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/tests/modules/user/authentification.spec.ts
- packages/api/tests/modules/user/user.spec.ts
> feat(api): add cli for update all users in brevo

- packages/api/migrations/20230804083206-add-profile-completed.js
- packages/api/package-lock.json
- packages/api/src/authentication/authentication.test.ts
- packages/api/src/modules/user/interfaces/http/AuthentificationController.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/shared/helpers/RepositoryHelper.test.ts
- packages/api/src/shared/helpers/__snapshots__/RepositoryHelper.test.ts.snap
- packages/api/tests/authentication/express.auth.hooks.test.ts
- packages/api/tests/modules/user/__snapshots__/consumer.cli.spec.ts.snap
- packages/api/tests/modules/user/__snapshots__/user.spec.ts.snap
- packages/api/tests/modules/user/repositories/__snapshots__/user.repository.test.ts.snap
- packages/api/tests/modules/user/repositories/user.repository.test.ts
- packages/dto/auth/TokenValidationDtoResponse.ts
- packages/dto/index.ts
- packages/dto/user/UserDto.ts
> feat(api): add token type information in validation token

- packages/front/src/lib/components/AutocompleteSelect/AutocompleteSelect.svelte
- packages/front/src/lib/components/AutocompleteSelect/combobox.css
- packages/front/src/lib/components/AutocompleteSelect/combobox.js
- packages/front/src/lib/components/AutocompleteSelect/licence.md
- packages/front/src/lib/core/Store.ts
- packages/front/src/lib/dsfr/Input.svelte
closes #1512 
[Capture vidéo du 2023-08-08 17-06-37.webm](https://github.com/betagouv/api-subventions-asso/assets/94919029/746df6a5-06a7-4a9a-934e-a1e25448fe2b)
> 1512 select autocomplete

- packages/api/src/modules/notify/notify.service.test.ts
- packages/api/src/modules/notify/notify.service.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
solves [DATA-SUBVENTION-API-1A](https://sentry.incubateur.net/organizations/betagouv/issues/58798)
> Fix login brevo

- packages/front/src/routes/(noAuth)/cgu/+page.svelte
> 1606 fix cgu height

- packages/front/src/routes/(home)/+page.svelte
- packages/front/src/routes/(home)/Home.controller.js
> fix(front): hide history if empty

- packages/front/src/routes/etablissement/[identifier]/components/TabsEtab.svelte
> fix(front): remove tabs etab centering

- packages/front/src/lib/dsfr/ModalFooter.svelte
- packages/front/src/lib/resources/users/user.service.js
- packages/front/src/lib/resources/users/user.service.test.js
- packages/front/src/routes/user/profile/Profile.controller.js
- packages/front/src/routes/user/profile/Profile.controller.test.js
- packages/front/src/routes/user/profile/components/ConfirmDeleteUserModal.svelte
- packages/front/src/routes/user/profile/components/DeleteUser.svelte
> 1603 fix delete account modal

- packages/front/src/lib/errors/StaticError.js
- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/services/requests.service.js
- packages/front/src/lib/services/requests.service.test.js
> 1605 fix login reload on error

- packages/front/src/lib/dsfr/ModalFooter.svelte
- packages/front/src/lib/errors/StaticError.js
- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/users/user.service.js
- packages/front/src/lib/resources/users/user.service.test.js
- packages/front/src/lib/services/requests.service.js
- packages/front/src/lib/services/requests.service.test.js
- packages/front/src/routes/(noAuth)/cgu/+page.svelte
- packages/front/src/routes/user/profile/Profile.controller.js
- packages/front/src/routes/user/profile/components/ConfirmDeleteUserModal.svelte
- packages/front/src/routes/user/profile/components/DeleteUser.svelte
Close preprod bugs (merged on develop because main is instable on build phase and will need lerna update)
> Fix 0.34.1

- packages/dto/auth/subscriptionForm/index.ts
- packages/dto/auth/subscriptionForm/territorialScope.ts
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/StructureStep.controller.ts
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/StructureStep.svelte
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/TerritorialCollectivitySubStep/TerritorialCollectivitySubStep.controller.ts
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/TerritorialCollectivitySubStep/TerritorialCollectivitySubStep.svelte
> 1527 step3 territorial collectivity

- packages/front/src/routes/auth/activate/[token]/components/StructureStep/CentralSubStep/CentralSubStep.controller.ts
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/CentralSubStep/CentralSubStep.svelte
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/OperatorSubStep/OperatorSubStep.svelte
- packages/front/src/routes/auth/activate/[token]/components/StructureStep/StructureStep.controller.ts
closes #1526 
closes #1528
Je les ai regroupés parce qu'il étaient chacun très petits
> 1526 1528 operator central

- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> feat(api): delete brevo contact after account deletion

- packages/api/src/cli.ts
- packages/api/src/configurations/mongo.conf.ts
- packages/api/src/cron.ts
- packages/api/src/modules/configurations/configurations.service.ts
- packages/api/src/modules/dump/dump.service.ts
- packages/api/src/modules/dump/interfaces/cli/DumpCliController.ts
- packages/api/src/modules/dump/interfaces/cron/DumpCronController.ts
- packages/api/src/modules/dump/repositories/metabase-dump.repository.ts
- packages/api/src/modules/stats/repositories/stats.repository.ts
- packages/api/src/modules/stats/repositories/statsAssociationsVisit.repository.ts
- packages/api/src/modules/stats/stats.service.ts
- packages/api/src/modules/user/user.service.ts
> feat(api): add metabase dump

- packages/api/src/decorators/cronController.decorator.test.ts
- packages/api/src/decorators/cronController.decorator.ts
> 1613 sentry cron

- packages/front/src/lib/components/Header/Header.svelte
- packages/front/src/lib/dsfr/SkipLinks.svelte
- packages/front/src/routes/+layout.svelte
> 1558 skiplinks

- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/lib/services/searchHistory.service.js
> 776 clean history logout

- packages/front/src/lib/components/Header/Header.svelte
- packages/front/src/lib/components/MultiStepForm/MultiStepForm.svelte
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.svelte
- packages/front/src/lib/dsfr/Button.svelte
- packages/front/src/lib/dsfr/GenericModal.svelte
- packages/front/src/routes/auth/forget-password/+page.svelte
- packages/front/src/routes/auth/login/+page.svelte
- packages/front/src/routes/auth/reset-password/[token]/+page.svelte
- packages/front/src/routes/auth/signup/+page.svelte
- packages/front/src/routes/etablissement/[identifier]/components/ContactEtab/ContactEtab.svelte
- packages/front/src/routes/user/profile/components/DeleteUser.svelte
> Rename tracker name

- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/__snapshots__/BrevoContactNotifyPipe.test.ts.snap
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> feat(api): update contact in brevo after activating account

- packages/api/src/modules/user/__snapshots__/user.service.test.ts.snap
- packages/api/src/modules/user/interfaces/cli/user.cli.controller.ts
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> 1124 get self user

- .github/workflows/main.yml
- package-lock.json
- packages/front/.env
- packages/front/package.json
- packages/front/src/hooks.client.ts
- packages/front/src/hooks.server.ts
- packages/front/svelte.config.js
- packages/front/vite.config.ts
> 1398 sentry front

- packages/api/src/authentication/authentication.test.ts
- packages/api/src/modules/user/__snapshots__/user.service.test.ts.snap
- packages/api/src/modules/user/interfaces/http/UserController.ts
- packages/api/src/modules/user/repositories/user.repository.ts
- packages/api/src/modules/user/user.migration.test.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/shared/helpers/RepositoryHelper.ts
- packages/api/tests/modules/user/__snapshots__/authentification.spec.ts.snap
- packages/api/tests/modules/user/user.service.test.ts
- packages/dto/user/UserDto.ts
> 1679 update user

- packages/api/src/modules/user/repositories/user.repository.ts
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
- packages/api/src/shared/helpers/RepositoryHelper.test.ts
- packages/api/src/shared/helpers/RepositoryHelper.ts
- packages/api/src/shared/helpers/__snapshots__/RepositoryHelper.test.ts.snap
- packages/api/tests/modules/user/__snapshots__/authentification.spec.ts.snap
- packages/api/tests/modules/user/authentification.spec.ts
- packages/front/src/lib/resources/auth/auth.port.js
- packages/front/src/lib/resources/auth/auth.port.test.js
- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/routes/(home)/+page.svelte
- packages/front/src/routes/(home)/Home.controller.js
- packages/front/src/routes/(home)/Home.controller.test.js
- packages/front/src/routes/auth/activate/[token]/ActivateAccount.controller.js
- packages/front/src/routes/auth/activate/[token]/ActivateAccount.controller.test.js
- packages/front/src/routes/auth/reset-password/[token]/ResetPwd.controller.js
- packages/front/src/routes/auth/reset-password/[token]/ResetPwd.controller.test.js
> 1561 1562 connect after pwd

- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsStatistique/SubventionsVersementsStatistique.controller.js
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsStatistique/SubventionsVersementsStatistique.svelte
> refactor(front): cleaned

- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/outPipes/MattermostNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/MattermostNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/__snapshots__/MattermostNotifyPipe.test.ts.snap
- packages/api/src/modules/user/user.service.test.ts
- packages/api/src/modules/user/user.service.ts
> 1702 domain mattermost alert

- packages/front/src/lib/components/MultiStepForm/MultiStepForm.svelte
- packages/front/src/routes/auth/activate/[token]/+page.svelte
- packages/front/src/routes/auth/activate/[token]/ActivateAccount.controller.js
- packages/front/src/routes/auth/activate/[token]/ActivateAccount.controller.test.js
> 1701 btn subcription tracking

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/api/CHANGELOG.md
- packages/api/jest.config.unit.env.ts
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/adapters/DemarchesSimplifieesDtoAdapter.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/adapters/DemarchesSimplifieesDtoAdapter.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.ts
- packages/api/src/modules/providers/demarchesSimplifiees/dto/DemarchesSimplifieesDto.ts
- packages/api/src/modules/providers/demarchesSimplifiees/queries/GetDossiersByDemarcheId.ts
> HOTFIX DS pagination

- packages/front/src/lib/store/modal.store.js
- packages/front/src/lib/store/modal.store.ts
- packages/front/src/routes/admin/users/composents/TableUsers.controller.ts
- packages/front/src/routes/admin/users/composents/TableUsers.svelte
- packages/front/src/routes/admin/users/list/+page.svelte
- packages/front/src/routes/admin/users/list/AdminUserAccountList.controller.ts
> 425 admin user store

- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/lib/services/searchHistory.service.js
> 1728 keep history

- package-lock.json
- packages/front/package.json
- packages/front/src/lib/types/jitbit-html-sanitizer.d.ts
- packages/front/src/routes/(home)/components/ResultCard.controller.ts
- packages/front/src/routes/(home)/components/ResultCard.svelte
> 1766 track history

- packages/front/src/global.css
- packages/front/src/routes/+layout.svelte
> 849 handle blue banner on error

- packages/front/src/lib/components/AutocompleteSelect/AutocompleteSelect.svelte
- packages/front/src/lib/dsfr/ModalFooter.svelte
- packages/front/src/lib/dsfr/Select.svelte
- packages/front/src/routes/user/profile/+page.svelte
- packages/front/src/routes/user/profile/Profile.controller.js
- packages/front/src/routes/user/profile/components/QuitNoSaveModal.svelte
profile 
- know why disabled save
- allow save after changing combobox
- allow leaving without save
> Fix v0.38.3 profile

- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
> fix(api): dont send empty values and fix first and last name

- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/shared/helpers/ObjectHelper.test.ts
- packages/api/src/shared/helpers/ObjectHelper.ts
> 1753 1754 api asso sentry errors

- packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.ts
quick fix pour les doubloons chorus en prod
je merge pas avant lundi pour en discuter @VSerain vu qu'on est déjà vendredi aprem
> fix(api): remove chorus line duplicates

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/src/lib/components/AutocompleteSelect/AutocompleteSelect.svelte
- packages/front/src/lib/components/AutocompleteSelect/combobox.js
> hotfix(front): combobox shows given value on init

- packages/front/src/lib/components/Documents/Documents.controller.js
- packages/front/src/lib/components/Documents/Documents.controller.test.js
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/resources/documents/documents.service.js
- packages/front/src/lib/resources/documents/documents.service.test.js
> 1386 dauphin docs token

- packages/api/src/modules/association-name/repositories/associationName.repository.ts
- packages/api/src/modules/stats/repositories/stats.repository.ts
voir #1874 pour une solution pour les logs 
et #969 refacto de toute façon `association-name`
> fix(api): comment indexes that conflict with current db state

- packages/api/src/modules/associations/associations.service.test.ts
- packages/api/src/modules/associations/associations.service.ts
- packages/api/src/modules/etablissements/etablissements.service.test.ts
- packages/api/src/modules/etablissements/interfaces/http/EtablissementController.ts
- packages/api/src/modules/grant/grant.service.test.ts
- packages/api/src/modules/grant/grant.service.ts
- packages/api/src/modules/subventions/subventions.service.test.ts
- packages/api/src/modules/subventions/subventions.service.ts
- packages/api/src/modules/versements/versements.service.test.ts
- packages/api/src/modules/versements/versements.service.ts
This reverts commit 6566043733a1c1dfc436bd438d217ae11cb4333e, reversing changes made to 7e218352257601becdb8eb834e77cf8da7236021.
> Revert "Merge pull request #1768 from betagouv/1406-no-ccas"

- packages/front/src/lib/components/InfosLegales/InfosLegales.controller.js
> fix(front): display establishment address

- packages/front/src/routes/search/[name]/Search.controller.ts
> fix(front): display input in SearchBar on search page first load

- packages/front/src/lib/components/SearchBar/SearchBar.svelte
> fix(front): disable search button if value is empty

- packages/front/src/lib/components/AssociationCard/AssociationCard.controller.test.ts
- packages/front/src/lib/components/AssociationCard/AssociationCard.controller.ts
- packages/front/src/lib/components/AssociationCard/AssociationCard.svelte
> fix(front): association card url with rna

- packages/front/src/routes/association/[identifier]/+page.svelte
- packages/front/src/routes/association/[identifier]/Association.controller.js
- packages/front/src/routes/association/[identifier]/Association.controller.test.js
> Fix not asso banner

- packages/front/src/lib/components/Stats/MonthlyGraph/MonthlyGraph.controller.test.js
- packages/front/src/routes/auth/forget-password/ForgetPwd.controller.test.js
- packages/front/src/routes/auth/reset-password/[token]/ResetPwd.controller.test.js
> fix(api): don't compare promises

- packages/api/src/modules/providers/chorus/@types/IChorusIndexedInformations.ts
- packages/api/src/modules/providers/chorus/__fixtures__/ChorusFixtures.ts
- packages/api/src/modules/providers/chorus/chorus.parser.test.ts
- packages/api/src/modules/providers/chorus/chorus.parser.ts
- packages/api/src/modules/providers/chorus/chorus.service.test.ts
- packages/api/src/modules/providers/chorus/chorus.service.ts
- packages/api/src/modules/providers/chorus/entities/ChorusLineEntity.ts
- packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.ts
A merge que quand on aura pu verifier qu'on est toujours iso prod
> fix(api): quick fix chorus line

- packages/api/src/dataProviders/api/rechercheEntreprises/RechercheEntreprisesAdapter.test.ts
- packages/api/src/dataProviders/api/rechercheEntreprises/RechercheEntreprisesAdapter.ts
- packages/api/src/dataProviders/api/rechercheEntreprises/RechercheEntreprisesDto.ts
- packages/api/src/dataProviders/api/rechercheEntreprises/rechercheEntreprises.port.test.ts
- packages/api/src/dataProviders/api/rechercheEntreprises/rechercheEntreprises.port.ts
- packages/api/src/modules/association-name/associationName.service.test.ts
- packages/api/src/modules/association-name/associationName.service.ts
- packages/api/src/modules/association-name/entities/AssociationNameEntity.ts
- packages/api/src/modules/providers/uniteLegalName/uniteLegal.name.service.test.ts
- packages/api/src/modules/providers/uniteLegalName/uniteLegal.name.service.ts
- packages/api/tests/modules/search.spec.ts
Closes #971 
closes #1917 
(ça marche pas sur une seule ligne)
> 971 add api recherche entreprise

- package-lock.json
- packages/front/package.json
- packages/front/src/lib/helpers/csvHelper.js
- packages/front/src/lib/helpers/csvHelper.test.js
> 1928 fix extract

- packages/front/src/lib/services/tracker.service.js
- packages/front/svelte.config.js
> feat(front): change url matomo

- packages/front/src/lib/components/Documents/components/DocumentCard.svelte
- packages/front/src/lib/dsfr/Card.svelte
- packages/front/src/lib/resources/documents/documents.service.js
> 1382 doc card

- packages/api/tools/osiris/deploy-osiris-files.js
pas grand chose mais c'est toujours ça
> feat(api): enhance osiris deploy tool description

- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
> fix(api): stringify body on sentry error in brevo contact

- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
> fix(api): send to sentry real error when brevo update crash

- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> fix(api): establishment can be undefined in api asso

- packages/front/src/global.css
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.js
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.test.js
- packages/front/src/lib/enums/IdentifierEnum.ts
- packages/front/src/lib/helpers/identifierHelper.test.ts
- packages/front/src/lib/helpers/identifierHelper.ts
- packages/front/src/lib/resources/associations/association.service.js
- packages/front/src/lib/resources/associations/association.service.test.js
- packages/front/src/lib/resources/open-source/rna-siren/rna-siren.port.test.ts
- packages/front/src/lib/resources/open-source/rna-siren/rna-siren.port.ts
- packages/front/src/lib/resources/open-source/rna-siren/rna-siren.service.test.ts
- packages/front/src/lib/resources/open-source/rna-siren/rna-siren.service.ts
- packages/front/src/routes/association/[identifier]/+page.svelte
- packages/front/src/routes/association/[identifier]/Association.controller.js
- packages/front/src/routes/association/[identifier]/Association.controller.test.js
- packages/front/src/routes/association/[identifier]/components/DuplicateAlert.controller.ts
- packages/front/src/routes/association/[identifier]/components/DuplicateAlert.svelte
- packages/front/src/routes/search/[name]/+page.svelte
- packages/front/src/routes/search/[name]/Search.controller.test.ts
- packages/front/src/routes/search/[name]/Search.controller.ts
> 1993 multi rna siren alert

- packages/api/migrations/20240118094300-add-last-activity-date-on-user.js
- packages/api/src/authentication/authentication.test.ts
- packages/api/src/middlewares/UserActivityMiddleware.ts
- packages/api/src/modules/user/services/crud/user.crud.service.ts
- packages/api/src/server.ts
- packages/api/src/shared/MongoConnection.ts
- packages/api/tests/interfaces/cli/__snapshots__/ConsumerInterfaceCli.spec.ts.snap
- packages/api/tests/modules/user/__snapshots__/authentification.spec.ts.snap
- packages/api/tests/modules/user/__snapshots__/user.spec.ts.snap
- packages/api/tests/modules/user/repositories/__snapshots__/user.repository.test.ts.snap
- packages/api/tests/modules/user/user.spec.ts
- packages/dto/user/UserDto.ts
> feat(api): add last activity date on user

- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/routes/auth/signup/Signup.controller.js
- packages/front/src/routes/auth/signup/Signup.controller.test.js
> fix(front): fix wrong error when user dont write email

- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.ts
> fix(api): fix error when ds return a 200 http code but wrong auth

- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> fix(api): dac documents is not an array its object

- packages/api/jest.config.integ.env.ts
- packages/api/jest.config.unit.env.ts
- packages/api/src/cron.ts
- packages/api/src/interfaces/cron/Rgpd.cron.ts
- packages/api/src/interfaces/http/User.http.ts
- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/notify.service.test.ts
- packages/api/src/modules/notify/notify.service.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/MattermostNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/MattermostNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/__snapshots__/BrevoContactNotifyPipe.test.ts.snap
- packages/api/src/modules/notify/outPipes/__snapshots__/MattermostNotifyPipe.test.ts.snap
- packages/api/src/modules/user/__fixtures__/user.fixture.ts
- packages/api/src/modules/user/repositories/user.repository.ts
- packages/api/src/modules/user/services/crud/user.crud.service.test.ts
- packages/api/src/modules/user/services/crud/user.crud.service.ts
- packages/api/src/modules/user/services/rgpd/__snapshots__/user.rgpd.service.test.ts.snap
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.test.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.ts
- packages/api/tests/interfaces/cron/Rgpd.cron.spec.ts
- packages/api/tests/interfaces/cron/__snapshots__/Rgpd.cron.spec.ts.snap
> feat(api): #1977 disable inactive for two years

- packages/api/jest.config.integ.env.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.ts
- packages/api/src/modules/user/repositories/user.repository.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.test.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.ts
- packages/api/tests/interfaces/cron/Rgpd.cron.spec.ts
- packages/api/tests/interfaces/cron/__snapshots__/Rgpd.cron.spec.ts.snap
closes #1031 
\+ informe les utilisateurs de la suppression de leur compte
~~attention au moment du merge (part d'une branche qui sera censée être squash)~~ :heavy_check_mark:
> feat(api): #1031 disable users never seen for 6 months and notify them

- packages/api/src/interfaces/cron/Rgpd.cron.ts
- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/@types/NotificationType.ts
- packages/api/src/modules/notify/@types/NotifyOutPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.ts
- packages/api/src/modules/user/services/rgpd/__snapshots__/user.rgpd.service.test.ts.snap
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.test.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.ts
- packages/api/tests/interfaces/cron/Rgpd.cron.spec.ts
closes #1032 
attention au moment du merge (part d'une branche qui sera censée être squash)
> feat(api): #1032 warn users before auto deletion because never seen

- packages/api/migrations/20240118094300-add-last-activity-date-on-user.js
encore un fix de préprod, mais la migration n'allait pas
> fix(api): lastActivityDate migration

- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.controller.js
> fix(front): do not update exercice if none is defined yet

- packages/api/src/cron.ts
about #2095 
ne fix pas, mais ça permet de se donner les moyens de faire un meilleur debug (on ne reproduit pas en local)
> feat(api): reactivate rgpd cron to test irl

- packages/api/src/interfaces/cli/Dump.cli.test.ts
- packages/api/src/interfaces/cli/Dump.cli.ts
- packages/api/src/modules/dump/__snapshots__/dump.pipedrive.parser.test.ts.snap
- packages/api/src/modules/dump/dump.pipedrive.parser.test.ts
- packages/api/src/modules/dump/dump.pipedrive.parser.ts
- packages/api/src/modules/dump/dump.service.test.ts
- packages/api/src/modules/dump/dump.service.ts
- packages/api/src/modules/dump/repositories/metabase-dump.repository.ts
> Metabase pipedrive user data

- packages/api/README.md
- packages/api/src/interfaces/http/Document.http.test.ts
- packages/api/src/interfaces/http/Document.http.ts
- packages/api/src/modules/documents/documents.service.test.ts
- packages/api/src/modules/documents/documents.service.ts
> feat(api): add multiple download files in zip

- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
j'ai refais une PR après une rebase develop volontaire mais totalement hors sujet :D
> refactor(api): set default date_modif_siren with a private method

- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsDashboard.svelte
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionsVersementsStatistique/SubventionsVersementsStatistique.svelte
- packages/front/src/lib/components/Tables/TableHead.svelte
- packages/front/src/lib/dsfr/Table.svelte
- packages/front/src/routes/association/[identifier]/Association.controller.ts
- packages/front/src/routes/association/[identifier]/components/Etablissements.svelte
> refactor(front): rewording and styling

- package-lock.json
- packages/api/package.json
> chore(api): remove vulnerable and unused package nodemailer

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/api/CHANGELOG.md
- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/configurations/mail.conf.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.test.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.ts
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/src/lib/components/Tables/TableHead.svelte
- couleurs finales des flèches qui se distinguent
- désactivation par variable d'env du cron de suppression des 6 mois pour que les gens soient bien tous prévenus
> Fix v0.45.2

- packages/api/src/modules/notify/outPipes/MattermostNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/__snapshots__/MattermostNotifyPipe.test.ts.snap
- packages/api/tests/interfaces/cron/__snapshots__/Rgpd.cron.spec.ts.snap
> feat(api): 2157 specific mattermost channel

- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.ts
- packages/api/src/modules/user/services/activation/user.activation.service.test.ts
- packages/api/src/modules/user/services/activation/user.activation.service.ts
- packages/api/src/modules/user/services/auth/user.auth.service.ts
- packages/api/src/modules/user/services/profile/user.profile.service.test.ts
- packages/api/src/modules/user/services/profile/user.profile.service.ts
> 2071 activated account

- packages/front/src/lib/dsfr/Pagination.svelte
- packages/front/src/routes/association/[identifier]/components/Establishments/Establishments.controller.ts
- packages/front/src/routes/association/[identifier]/components/Etablissements.svelte
> feat(front): add pagination on etablissements

- .github/workflows/main.yml
> chore: 2191 github ci run tests in parallel

- packages/front/src/lib/dsfr/Pagination.svelte
- packages/front/src/routes/association/[identifier]/components/Establishments/Establishments.svelte
> feat(front): #2229 truncate pagination 

- packages/api/src/interfaces/cron/SearchCache.cron.ts
- packages/api/src/interfaces/http/Search.http.ts
- packages/api/src/modules/search/repositories/entities/searchCacheDbo.ts
- packages/api/src/modules/search/repositories/search.repository.ts
- packages/api/src/modules/search/search.service.test.ts
- packages/api/src/modules/search/search.service.ts
- packages/api/tests/modules/__snapshots__/search.spec.ts.snap
- packages/api/tests/modules/search.spec.ts
- packages/dto/search/AssociationNameDto.ts
closes #1210
à merger quand la pr front est prête
> feat(api): 1210 search pagination

- packages/front/src/lib/components/SearchBar/SearchBar.svelte
- packages/front/src/lib/resources/associations/association.port.test.ts
- packages/front/src/lib/resources/associations/association.port.ts
- packages/front/src/lib/resources/associations/association.service.test.ts
- packages/front/src/lib/resources/associations/association.service.ts
- packages/front/src/routes/search/[name]/+page.svelte
- packages/front/src/routes/search/[name]/Search.controller.test.ts
- packages/front/src/routes/search/[name]/Search.controller.ts
closes #2065 
stuck by #2231 , #2205
missing some testing on Search.controller but can be reviewed
> 2065 search pagination front

- packages/api/src/interfaces/cli/Scdl.cli.ts
- packages/api/src/modules/providers/chorus/chorus.parser.test.ts
- packages/api/src/modules/providers/chorus/chorus.parser.ts
> feat(api): update chorus parser with new xlsx format

- packages/front/src/lib/components/Documents/Documents.controller.test.ts
- packages/front/src/lib/components/Documents/Documents.controller.ts
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/helpers/csvHelper.js
- packages/front/src/lib/helpers/document.helper.test.ts
- packages/front/src/lib/helpers/document.helper.ts
- packages/front/src/lib/helpers/promiseHelper.js
- packages/front/src/lib/resources/associations/association.service.ts
- packages/front/src/lib/resources/document/document.port.ts
- packages/front/src/lib/resources/document/document.service.ts
- packages/front/src/lib/resources/establishments/establishment.service.ts
- packages/front/src/routes/search/[name]/Search.controller.ts
> feat(front): #2203 download docs front

- packages/front/src/global.css
- packages/front/src/lib/components/AssociationCard/AssociationCard.svelte
- packages/front/src/routes/(home)/+page.svelte
- packages/front/src/routes/auth/forget-password/+page.svelte
- packages/front/src/routes/search/[name]/+page.svelte
> feat(front): #2222 #2223 promote identifiers

- packages/front/src/lib/helpers/identifierHelper.test.ts
- packages/front/src/lib/helpers/identifierHelper.ts
- packages/front/src/lib/helpers/stringHelper.js
- packages/front/src/lib/helpers/stringHelper.test.js
- packages/front/src/routes/search/[name]/+page.svelte
- packages/front/src/routes/search/[name]/Search.controller.test.ts
- packages/front/src/routes/search/[name]/Search.controller.ts
> feat(front): display alert if search concerns a company

- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/demarchesSimplifiees.service.ts
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/README.md
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-62744-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-62746-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-62747-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-75747-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-78102-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-78125-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-78126-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-78128-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-79485-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-86113-form.json
- packages/api/src/modules/providers/demarchesSimplifiees/schemas/schema-base.json
> feat(api): #2186 more DS schemas

- packages/front/src/lib/components/AssociationCard/AssociationCard.svelte
- packages/front/src/lib/dsfr/Card.svelte
- packages/front/src/routes/association/[identifier]/components/EstablishmentCard.svelte
> feat(front): give min height to title card with ellipsis

- packages/api/src/modules/providers/chorus/@types/IChorusIndexedInformations.ts
- packages/api/src/modules/providers/chorus/README.md
> docs(api): create chorus README

- packages/api/src/modules/providers/apiAsso/__fixtures__/RnaStructureFixture.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/adapters/__snapshots__/ApiAssoDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/apiAsso/dto/RnaStructureDto.ts
- packages/dto/associations/Association.ts
- packages/dto/associations/AssociationNature.ts
> feat(api): retrieve association public utility from api asso

- packages/api/src/modules/providers/apiAsso/__fixtures__/RnaStructureFixture.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/adapters/__snapshots__/ApiAssoDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/apiAsso/dto/RnaStructureDto.ts
- packages/dto/associations/Association.ts
- packages/dto/associations/AssociationNature.ts
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.js
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.test.js
- packages/front/src/lib/components/StructureTitle/StructureTitle.svelte
- packages/front/src/routes/+layout.svelte
> feat(front): display asso is public utility

- packages/api/src/modules/providers/apiAsso/__fixtures__/RnaStructureFixture.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/adapters/__snapshots__/ApiAssoDtoAdapter.test.ts.snap
- packages/api/src/modules/providers/apiAsso/dto/RnaStructureDto.ts
- packages/dto/associations/Association.ts
- packages/dto/associations/AssociationNature.ts
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.js
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.test.js
- packages/front/src/lib/components/StructureTitle/StructureTitle.svelte
- packages/front/src/routes/+layout.svelte
Close #2228 
Idem ici je reprend 2227 mais pour le squash merge il va falloir voir ce que ça fait
> 2228 display nb estab on asso page

- packages/front/src/routes/etablissement/[identifier]/components/ContactEtab/ContactEtab.svelte
- packages/front/src/routes/etablissement/[identifier]/components/ContactEtab/ContactEtabController.js
- packages/front/src/routes/etablissement/[identifier]/components/ContactEtab/ContactEtabController.test.js
- packages/front/src/routes/etablissement/[identifier]/components/InfosBancairesEtab/InfosBancairesEtab.controller.js
- packages/front/src/routes/etablissement/[identifier]/components/InfosBancairesEtab/InfosBancairesEtab.controller.test.js
- packages/front/src/routes/etablissement/[identifier]/components/InfosBancairesEtab/InfosBancairesEtab.svelte
> feat(front): hide tables and display message in empty data tabs

- packages/api/migrations/20240329101306-add-exercice-field-if-not-exists.js
> feat(api): add exercice field if not exists

- packages/front/src/lib/services/crisp.service.ts
- packages/front/src/routes/association/[identifier]/components/Bodacc/Bodacc.controller.js
- packages/front/src/routes/association/[identifier]/components/Bodacc/Bodacc.svelte
> feat(front): crisp event on visiting bodacc tab

- packages/front/src/routes/association/[identifier]/components/Establishments/Establishments.controller.test.ts
- packages/front/src/routes/association/[identifier]/components/Establishments/Establishments.controller.ts
> feat(front): display nb estab in activity in estabs tab

- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.js
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.controller.test.js
- packages/front/src/lib/components/SubventionsVersementsDashboard/SubventionTable/SubventionTable.svelte
> feat(front): display amount if status is granted

- packages/api/src/modules/dump/repositories/metabase-dump.repository.ts
> feat(front): #2302 pipedrive upserts itself

- packages/api/migrations/20240506153247-preventive_anonymisation.js
- packages/api/src/middlewares/LogMiddleware.ts
- packages/api/src/modules/stats/repositories/stats.repository.ts
- packages/api/src/modules/user/__fixtures__/user.fixture.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.test.ts
- packages/api/src/modules/user/services/rgpd/user.rgpd.service.ts
closes #2300 
closes #2126
misses tests
> 2300 fix rgpd anonymization

- packages/front/src/global.css
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/components/Documents/components/DocumentCard.svelte
- packages/front/src/lib/dsfr/Card.svelte
> feat(front): #2307 new document design

- .gitignore
depuis la mise à jour de lerna
> feat: add new nx folder location in .gitignore

- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/routes/auth/login/Login.controller.js
- packages/front/src/routes/auth/login/Login.controller.test.js
> refactor(front): #2356 redirect through localStorage

- packages/front/src/lib/components/StructureTitle/StructureTitle.svelte
> fix(front): display nb estabs every time

- packages/api/src/modules/notify/@types/NotificationDataTypes.ts
- packages/api/src/modules/notify/notify.service.ts
- packages/api/src/modules/notify/outPipes/BrevoContactNotifyPipe.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.test.ts
- packages/api/src/modules/notify/outPipes/BrevoMailNotifyPipe.ts
- packages/api/src/modules/user/services/agentConnect/user.agentConnect.service.test.ts
- packages/api/src/modules/user/services/agentConnect/user.agentConnect.service.ts
- packages/api/src/modules/user/services/crud/user.crud.service.ts
> feat(api): #2381 agent connect creation email

- packages/front/src/lib/components/Documents/Documents.controller.test.ts
- packages/front/src/lib/components/Documents/Documents.controller.ts
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/components/Documents/components/OpenCloseButton.svelte
- packages/front/src/lib/dsfr/Accordeon.svelte
- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/lib/resources/document/document.service.ts
- packages/front/src/routes/auth/login/Login.controller.js
- packages/front/src/routes/auth/login/Login.controller.test.js
> feat(front): #2311 show all docs button

- packages/api/src/interfaces/http/Document.http.test.ts
- packages/api/src/interfaces/http/Document.http.ts
- packages/api/src/modules/associations/associations.service.test.ts
- packages/api/src/modules/documents/@types/DocumentsProvider.ts
- packages/api/src/modules/documents/document.adapter.ts
- packages/api/src/modules/documents/documents.service.test.ts
- packages/api/src/modules/documents/documents.service.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/api/src/modules/providers/avisSituationInsee/avisSituationInsee.service.ts
- packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/dto/associations/index.ts
- packages/dto/documents/DocumentDto.ts
- packages/dto/documents/DocumentRequestDto.ts
- packages/dto/documents/GetDocumentsResponseDto.ts
- packages/dto/documents/index.ts
- packages/dto/index.ts
- packages/dto/search/index.ts
- packages/front/src/lib/resources/associations/association.port.ts
- packages/front/src/lib/resources/establishments/establishment.port.ts
> feat(api,dto): #2309 download selected docs

- packages/front/src/lib/dsfr/Checkbox.svelte
- packages/front/src/routes/auth/signup/+page.svelte
- packages/front/src/routes/auth/signup/Signup.controller.js
- packages/front/src/routes/auth/signup/Signup.controller.test.js
> feat(front): #2432 checkbox agent work ethic

- packages/api/src/modules/documents/documents.service.test.ts
- packages/api/src/modules/documents/documents.service.ts
- packages/front/src/lib/components/Documents/Documents.controller.test.ts
- packages/front/src/lib/components/Documents/Documents.controller.ts
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/components/Documents/components/DocumentCard.controller.test.ts
- packages/front/src/lib/components/Documents/components/DocumentCard.controller.ts
- packages/front/src/lib/components/Documents/components/DocumentCard.svelte
- packages/front/src/lib/resources/document/document.adapter.test.ts
- packages/front/src/lib/resources/document/document.adapter.ts
- packages/front/src/lib/resources/document/document.port.ts
- packages/front/src/lib/resources/document/document.service.test.ts
- packages/front/src/lib/resources/document/document.service.ts
> feat(front): #2308 select docs to group download 

- packages/front/src/lib/components/Documents/Documents.controller.ts
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/components/Documents/components/DocumentCard.controller.ts
- packages/front/src/lib/components/Documents/components/DocumentCard.svelte
> feat(front): docs reset selection

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/front/CHANGELOG.md
- packages/front/package-lock.json
- packages/front/package.json
- packages/front/src/lib/components/MainInfoBanner/MainInfoBanner.controller.test.ts
- packages/front/src/lib/components/MainInfoBanner/MainInfoBanner.controller.ts
- packages/front/src/lib/components/MainInfoBanner/MainInfoBanner.svelte
- packages/front/src/lib/dsfr/InformationBanner.svelte
- packages/front/src/routes/App.controller.test.ts
- packages/front/src/routes/App.controller.ts
- packages/front/src/routes/user/profile/Profile.controller.js
> hotfeat(front): #2536 consultation notice 

- packages/front/src/lib/components/Documents/components/DocumentCard.controller.ts
> fix(front): #2532 small mistake about doc selection

- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
- packages/front/src/lib/components/Documents/Documents.controller.test.ts
- packages/front/src/lib/components/Documents/Documents.controller.ts
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/components/Documents/components/DocumentCard.controller.test.ts
- packages/front/src/lib/components/Documents/components/DocumentCard.controller.ts
- packages/front/src/lib/components/Documents/components/DocumentCard.svelte
- packages/front/src/lib/components/Documents/components/DocumentSection.svelte
- packages/front/src/lib/components/Documents/components/DownloadButton.controller.ts
- packages/front/src/lib/components/Documents/components/DownloadButton.svelte
> feat(front): #2533 new docs categorization

- packages/api/src/interfaces/cli/Scdl.cli.test.ts
- packages/api/src/interfaces/cli/Scdl.cli.ts
- packages/api/src/modules/providers/scdl/scdl.grant.parser.test.ts
- packages/api/src/modules/providers/scdl/scdl.grant.parser.ts
- packages/api/src/modules/providers/scdl/scdl.mapper.ts
> feat(api): #2490 lyon data config

- packages/api/src/interfaces/cli/Osiris.cli.ts
- packages/api/src/modules/providers/osiris/README.md
- packages/api/src/modules/providers/osiris/parse osiris.md
- packages/api/src/shared/GenericParser.ts
- packages/api/tools/osiris/deploy-files-container.sh
- packages/api/tools/osiris/deploy-osiris-files.js
- packages/tools/osiris-automation/index.js
closes #2498 
J'étais pas sûre d'où mettre le fichier de doc
> feat(api, tools): #2498 resilient doc osiris

- packages/api/src/modules/grant/@types/rawGrant.ts
- packages/api/src/modules/providers/chorus/chorus.service.test.ts
- packages/api/src/modules/providers/chorus/chorus.service.ts
- packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.ts
Je l'ai comparé à la première branch modifié de façon que ça soit mis en lumière que les différences supplémentaires
> feat(api): findAll and getAllPayments added

- packages/api/src/dataProviders/db/paymentFlat/PaymentFlat.adapter.test.ts
- packages/api/src/dataProviders/db/paymentFlat/PaymentFlat.adapter.ts
- packages/api/src/dataProviders/db/paymentFlat/PaymentFlatDbo.ts
- packages/api/src/dataProviders/db/paymentFlat/__fixtures__/paymentFlatDbo.fixture.ts
- packages/api/src/dataProviders/db/paymentFlat/__fixtures__/paymentFlatEntity.fixture.ts
- packages/api/src/dataProviders/db/paymentFlat/paymentFlat.port.test.ts
- packages/api/src/dataProviders/db/paymentFlat/paymentFlat.port.ts
- packages/api/src/entities/PaymentFlatEntity.ts
The branch is comparerd with 2526-pass-plate-method-chorus. Je ne comprends pas pourquoi les tests ne sont pas lancés sur cette branch.
> add paymentFlatPort

- packages/api/src/dataProviders/db/paymentFlat/PaymentFlatDbo.ts
- packages/api/src/entities/PaymentFlatEntity.ts
- packages/api/src/modules/data-viz/paymentFlat/__fixtures__/chorusLineEntity.fixture.ts
- packages/api/src/modules/data-viz/paymentFlat/__fixtures__/dataBretagne.fixture.ts
- packages/api/src/modules/data-viz/paymentFlat/__fixtures__/paymentFlatEntity.fixture.ts
- packages/api/src/modules/data-viz/paymentFlat/paymentFlat.service.test.ts
- packages/api/src/modules/data-viz/paymentFlat/paymentFlat.service.ts
- packages/api/src/modules/data-viz/paymentFlat/paymentFlatAdapter.test.ts
- packages/api/src/modules/data-viz/paymentFlat/paymentFlatAdapter.ts
- packages/api/src/modules/providers/chorus/chorus.service.test.ts
- packages/api/src/modules/providers/chorus/chorus.service.ts
- packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.test.ts
- packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.ts
Compared to 2524 payment flat port. Là aussi il me fait que le test de securité quand je push la branche et pas les tests unitaires.. je ne comprens pas pourquoi :/
> 2523 payment flat service

- package-lock.json
- packages/api/package.json
- packages/api/src/server.ts
closes #2588
Maintenant il faut décider de quelle est la limite. J'ai laissé les valeurs d'exemple
> feat(api): #2588 rate limit

- package-lock.json
- packages/front/package.json
- packages/front/src/lib/components/Footer.svelte
- packages/front/src/lib/components/InfosLegales/MoreInfosLegalesModal.svelte
- packages/front/src/lib/components/MainInfoBanner/MainInfoBanner.controller.ts
- packages/front/src/lib/components/MainInfoBanner/MainInfoBanner.svelte
- packages/front/src/lib/components/SubventionsPaymentsDashboard/PaymentTable/PaymentTable.controller.js
- packages/front/src/lib/components/SubventionsPaymentsDashboard/PaymentTable/PaymentTable.svelte
- packages/front/src/lib/components/SubventionsPaymentsDashboard/PaymentTable/__snapshots__/PaymentTable.controller.test.js.snap
- packages/front/src/lib/components/SubventionsPaymentsDashboard/SubventionTable/SubventionTable.controller.js
- packages/front/src/lib/components/SubventionsPaymentsDashboard/SubventionTable/SubventionTable.svelte
- packages/front/src/lib/components/SubventionsPaymentsDashboard/SubventionsPaymentsDashboard.svelte
- packages/front/src/lib/components/SubventionsPaymentsDashboard/SubventionsPaymentsStatistique/SubventionsPaymentsStatistique.controller.ts
- packages/front/src/lib/components/SubventionsPaymentsDashboard/SubventionsPaymentsStatistique/SubventionsPaymentsStatistique.svelte
- packages/front/src/lib/components/Tables/NumberTableCell.svelte
- packages/front/src/lib/components/Tables/TableCell.svelte
- packages/front/src/lib/components/Tables/TableHead.svelte
- packages/front/src/lib/dsfr/Button.svelte
- packages/front/src/lib/dsfr/InformationBanner.svelte
- packages/front/src/lib/dsfr/Table.svelte
- packages/front/src/routes/admin/users/composents/TableUsers.svelte
- packages/front/src/routes/admin/users/list/AdminUserAccountList.controller.ts
- packages/front/src/routes/etablissement/[identifier]/components/InfosBancairesEtab/InfosBancairesEtab.svelte
> feat(front): #2560 upgrade dsfr to 1.12 with tables

- packages/front/src/lib/components/Documents/Documents.controller.test.ts
- packages/front/src/lib/components/Documents/Documents.controller.ts
> fix(front): #2611 docs when no siren

- packages/front/src/routes/search/[name]/Search.controller.test.ts
- packages/front/src/routes/search/[name]/Search.controller.ts
> fix(front): #2171 #2289 handle spaces in search

- packages/api/src/interfaces/sse/Association.sse.ts
- packages/front/src/routes/association/[identifier]/Association.controller.ts
> feat: resolve sse wrong answer and unessary call to api

- packages/api/src/interfaces/http/Provider.http.ts
- packages/api/src/modules/data-log/dataLog.adapter.ts
- packages/api/src/modules/data-log/dataLog.service.test.ts
- packages/api/src/modules/data-log/dataLog.service.ts
- packages/api/src/modules/data-log/repositories/dataLog.repository.ts
- packages/api/tests/interfaces/http/__snapshots__/providers.spec.ts.snap
- packages/api/tests/interfaces/http/providers.spec.ts
- packages/dto/index.ts
- packages/dto/providers/dataLog.ts
> feat(api,dto): #2589 data log route

- packages/api/src/interfaces/cli/Fonjep.cli.test.ts
- packages/api/src/interfaces/cli/Fonjep.cli.ts
- packages/api/src/interfaces/cli/Scdl.cli.test.ts
- packages/api/src/interfaces/cli/Scdl.cli.ts
- packages/api/src/interfaces/cli/Subventia.cli.ts
- packages/api/src/shared/CliController.test.ts
- packages/api/src/shared/CliController.ts
- packages/api/src/shared/errors/cliErrors/ExportDateError.ts
- packages/api/src/shared/errors/cliErrors/FormatDateError.ts
- packages/api/src/shared/errors/cliErrors/ObsoleteDateError.ts
- packages/api/src/shared/errors/cliErrors/OutOfRangeDateError.ts
- packages/api/tests/interfaces/cli/SubventiaInterfaceCli.spec.ts
> 2646 make cli export date mandatory

- packages/front/src/lib/components/MultiStepForm/MultiStepForm.controller.test.ts
- packages/front/src/lib/components/MultiStepForm/MultiStepForm.controller.ts
- packages/front/src/lib/components/MultiStepForm/MultiStepForm.svelte
- packages/front/src/lib/components/MultiStepForm/Step.ts
- packages/front/src/routes/auth/activate/[token]/+page.svelte
refacto front non liée à un ticket
> refactor(front): migrate multi step form to typescript

- packages/api/src/modules/providers/demarchesSimplifiees/adapters/DemarchesSimplifieesEntityAdapter.test.ts
- packages/api/src/modules/providers/demarchesSimplifiees/adapters/DemarchesSimplifieesEntityAdapter.ts
- packages/api/tests/interfaces/http/__snapshots__/associations.spec.ts.snap
> feat(api): #2671 map demarches simplifiees status

- packages/api/src/middlewares/LogMiddleware.test.ts
- packages/api/src/middlewares/LogMiddleware.ts
> fix(api): #2655 keep user id in logs

- packages/front/src/lib/components/SubventionsPaymentsDashboard/PaymentTable/PaymentTable.controller.js
- packages/front/src/lib/components/SubventionsPaymentsDashboard/PaymentTable/PaymentTable.svelte
> feat(front): display nothing on payment cell if sub is refused

- packages/api/src/modules/providers/osiris/README.md
- packages/api/src/shared/GenericParser.test.ts
- packages/api/src/shared/GenericParser.ts
closes #2688 
closes #2622
va demander de réimporter osiris 2024
> fix(api): #2688 fix osiris status

- packages/api/src/interfaces/http/Authentification.http.ts
- packages/api/src/server.ts
> fix(api): #2653 cors config differentiates front and consumer calls

- packages/api/src/modules/documents/documents.service.test.ts
- packages/api/src/modules/documents/documents.service.ts
Le 1er commit fix : #YWH-PGM11287-7 - #YWH-PGM11287-8 - #YWH-PGM11287-9
Le 2em commit fix : #YWH-PGM11287-2 #YWH-PGM11287-3
closes #2659
> fix(api): check url of document behind call

- packages/api/src/modules/providers/scdl/scdl.mapper.test.ts
- packages/api/src/modules/providers/scdl/scdl.mapper.ts
> fix(api): #2656 adapts amounts with spaces in string

- packages/api/src/modules/providers/osiris/entities/OsirisRequestEntity.ts
> fix(api): comprehend new osiris paths

- packages/front/src/lib/components/MainInfoBanner/MainInfoBanner.controller.ts
> feat(front): #2788 changer main banner content

- packages/api/jest.config.integ.setup.ts
- packages/api/src/dataProviders/db/paymentFlat/paymentFlat.port.ts
- packages/api/src/modules/grant/grant.service.test.ts
- packages/api/src/modules/grant/grant.service.ts
- packages/api/src/modules/grant/grantExtract.service.test.ts
- packages/api/src/modules/grant/grantExtract.service.ts
- packages/api/src/modules/payments/payments.service.test.ts
- packages/api/src/modules/payments/payments.service.ts
- packages/api/src/modules/providers/scdl/repositories/miscScdlProducer.repository.ts
- packages/api/src/modules/subventions/subventions.service.ts
- packages/api/tests/dataProviders/db/__fixtures__/scdl.fixtures.ts
- packages/api/tests/interfaces/cli/PaymentsFlatInterfaceCli.spec.ts
- packages/api/tests/interfaces/http/__snapshots__/associations.spec.ts.snap
- packages/api/tests/interfaces/http/associations.spec.ts
"corrige" également un test de paymentFlat mais sans comprendre comment (j'avais une erreur sur un versement chorus (le "3") qui ne remontait plus.
J'ai refacto un peu le test pour y voir plus claire et ça a corriger l'erreur.. intriguant. Mais à priori pas du tout lié à ma PR
> feat(api): flatten payment by exercise year and order grant results

- packages/api/migrations/20241023153926-formatted-dauphin-id.js
- packages/api/src/interfaces/cli/Gispro.cli.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.ts
- packages/api/src/modules/providers/dauphin/repositories/dauphin-gispro.repository.ts
- packages/api/src/modules/providers/gispro/entities/gisproLineEntity.test.ts
- packages/api/src/modules/providers/gispro/entities/gisproLineEntity.ts
- packages/api/src/modules/providers/gispro/gispro.parser.ts
- packages/api/src/shared/CliController.test.ts
- packages/api/src/shared/CliController.ts
closes #2322
closes #2711 
closes #2708
closes #2709 
closes #2710
> feat(api): #2322 get EJ from gispro data

- packages/api/src/modules/grant/grantExtract.service.test.ts
- packages/api/src/modules/grant/grantExtract.service.ts
> fix(api): add csv extension and add bom for utf8

- packages/front/src/lib/components/Auth/Auth.controller.ts
- packages/front/src/lib/helpers/identifierHelper.test.ts
- packages/front/src/lib/helpers/identifierHelper.ts
- packages/front/src/routes/association/[identifier]/Association.controller.ts
> fix(front): redirect to estab page if identifier is a siret

- packages/front/src/lib/components/Documents/Documents.controller.ts
- packages/front/src/lib/components/Documents/Documents.svelte
- packages/front/src/lib/helpers/identifierHelper.ts
> 2883 load docs on asso without rna

- packages/api/migrations/20241125174234-userId_objectId_in_visits.js
- packages/api/src/middlewares/LogMiddleware.ts
> fix(api): #2872 userId as string only in logs

- packages/api/src/modules/providers/scdl/scdl.mapper.ts
> feat(api): #2917 data integration centre val de loire 2021

- packages/api/src/modules/providers/scdl/scdl.mapper.ts
Reverts betagouv/api-subventions-asso#2939
> Revert "feat(api): #2917 data integration centre val de loire 2021"

- packages/front/src/lib/components/Documents/components/DownloadButton.controller.ts
- packages/front/src/lib/components/Documents/components/DownloadButton.svelte
https://github.com/betagouv/api-subventions-asso/issues/2847
> fix(front): disables the reset button when no document is selected + rename

- packages/api/src/dataProviders/db/rnaSiren/rnaSiren.port.ts
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.ts
- packages/front/src/routes/etablissement/[identifier]/Establishment.controller.ts
closes #2994 
Le pb semblait venir du fait que l'asso n'avait pas de rna, dont on avait besoin dans la façon dont marchait la page
> fix(front): #2994 get estab data when no rna can be found

- packages/front/src/routes/auth/reset-password/[token]/+page.svelte
- packages/front/src/routes/user/profile/+page.svelte
closes #2995
Le formulaire n'était juste pas soumis
> fix(front): #2995 confusion between type and htmlType

- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
- packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.ts
closes #2551
J'ai pas pu le tester ça n'arrive plus
> feat(api): #2551 transforms api-asso localhost url to actual domain

- packages/front/src/lib/components/GrantDashboard/application.helper.ts
> feat(front): #2993 if no granted amount display label

- packages/api/src/modules/providers/scdl/scdl.mapper.ts
Closes #3003 
En complément :
- ajout d'un parser de nombre en string dans les adapters des sirets pour le cas des fichier .xls avec colonne au format nombre
> feat(api): #3003 data integration IHEDN

- packages/front/src/lib/components/AssociationCard/AssociationCard.controller.test.ts
- packages/front/src/lib/components/AssociationCard/AssociationCard.controller.ts
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.test.ts
- packages/front/src/lib/components/StructureTitle/StructureTitle.controller.ts
> fix(front): #2977 one or no establishment is not the same

- packages/front/src/lib/components/GrantDashboard/Modals/PaymentsInfoModal.svelte
- packages/front/src/lib/components/GrantDashboard/application.helper.ts
Diagnostics : 
- les infos manquantes fonjep sont des infos qu'on sait qu'on n'a pas, encore faut-il afficher proprement qu'on n'a pas l'info
- le programme n'est plus associé à son libellé au même endroit, je mets ce calcul dans la modale
closes #3062
closes #3064
> fix(front): #3062 #3064 payment modale

- packages/front/src/lib/components/GrantDashboard/GrantDashboard.controller.test.ts
- packages/front/src/lib/components/GrantDashboard/GrantDashboard.controller.ts
- packages/front/src/lib/components/GrantDashboard/GrantDashboard.svelte
> fix(front): #3063 exercise label

- packages/api/src/modules/documents/documents.service.test.ts
- packages/api/src/modules/documents/documents.service.ts
> fix(api): #2733 no slash doc name on download

- packages/api/src/modules/providers/scdl/scdl.grant.parser.ts
- packages/api/src/modules/providers/scdl/scdl.mapper.ts
Cette PR inclue aussi un léger refactoring des requirements. La propriété "optional" devient obligatoire pour rendre plus explicite le caractère obligatoire ou non des champs du scdl
> feat(api): #3032 data integration deux-sevres

- packages/api/README.md
- packages/api/jest.config.integ.setup.ts
- packages/api/src/modules/user/services/agentConnect/user.agentConnect.service.ts
- packages/api/src/modules/user/services/check/user.check.service.test.ts
- packages/api/src/modules/user/services/check/user.check.service.ts
- packages/api/src/modules/user/services/crud/user.crud.service.test.ts
- packages/api/src/modules/user/services/crud/user.crud.service.ts
- packages/api/src/server.ts
- packages/api/tests/__helpers__/tokenHelper.ts
- packages/api/tests/modules/user/user.agentConnect.spec.ts
- packages/front/.env
- packages/front/README.md
- packages/front/src/lib/dsfr/Button.svelte
- packages/front/src/lib/dsfr/Table.svelte
- packages/front/src/lib/helpers/stringHelper.js
- packages/front/svelte.config.js
> feat(api): #3045 no control on agent connect email domains

- packages/api/src/modules/user/services/activation/user.activation.service.test.ts
- packages/api/src/modules/user/services/activation/user.activation.service.ts
- packages/api/src/modules/user/services/crud/__snapshots__/user.crud.service.test.ts.snap
- packages/api/src/modules/user/services/crud/user.crud.service.test.ts
- packages/api/src/modules/user/services/crud/user.crud.service.ts
- packages/dto/user/UserDto.ts
> feat(api): #2851 reset link in list-user admin root

- packages/front/src/lib/resources/associations/association.service.ts
au passage de #1171 mais qui en fait était déjà faite
> fix(front): proper type given

- .husky/pre-push
Proposition de ne plus avoir les tests au push, vu que le ci tourne derrière (quitte à créer une PR draft)
> ci(root): no pre-push tests (cf ci)

- packages/api/src/interfaces/http/Consumer.http.ts
> feat(api): #3110 create consomer via http route

- packages/front/src/lib/components/Footer.svelte
> feat(front): add security breach link in footer

- .github/workflows/check-pr-title.yml
> ci: #3186 add github action to validate pull request name

- packages/api/src/modules/providers/fonjep/fonjep.parser.old.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.parser.old.ts
- packages/api/src/modules/providers/fonjep/fonjep.parser.test.ts
- packages/api/src/modules/providers/fonjep/fonjep.parser.ts
- packages/api/src/shared/GenericParser.test.ts
- packages/api/src/shared/GenericParser.ts
closes #3191
nouvel onglet "Cofinancement" non exploité dans cette PR
> feat(api): #3191 fonjep new format

- packages/api/src/modules/providers/sirene/stockUniteLegale/parser/sireneStockUniteLegale.parser.ts
> fix(api): #3047 ensure to not overload batch

- packages/api/migrations/20241007125734-fill-data-log-with-first-import.js
- packages/api/src/modules/port.list.ts
> feat(api): #2703 add first import for each raw provider

- packages/front/src/lib/resources/dataViz/dataViz.service.ts
- packages/front/src/routes/dataviz/+page.svelte
- packages/front/src/routes/dataviz/DataViz.controller.test.ts
- packages/front/src/routes/dataviz/DataViz.controller.ts
- packages/front/src/routes/dataviz/components/TableAmountsVsProgramRegion/TableAmountsVsProgramRegion.controller.test.ts
- packages/front/src/routes/dataviz/components/TableAmountsVsProgramRegion/TableAmountsVsProgramRegion.controller.ts
- packages/front/src/routes/dataviz/components/TableAmountsVsProgramRegion/TableAmountsVsProgramRegion.svelte
- packages/front/src/routes/dataviz/components/TableAmountsVsProgramRegion/__fixtures__/TableAmountsVsProgramRegion.fixture.ts
@mxmeunier @alice-telescoop, 
J'ai fait les modifs, j'ai ajouté un filtre sur les données. Or, les données pour le moment ne sont pas ordonnées dans la table. Je laisserai comme ça pour le moment et j'avancerai. Pour moi ça sera le sujet d'un autre ticket vu que la priorité c'est d'avoir un prototype même si dirty. Qu'est-ce que vous en pensez ?
> feat(front): #3160  wip add amountsVsProgramRegion table

- packages/api/tools/osiris/deploy-osiris-files.js
- packages/tools/osiris-automation/Osiris/OsirisExtractDownloader.js
- packages/tools/osiris-automation/Osiris/OsirisPosibilitiesBuilder.js
closes #3215 
C'est qque chose que j'ai fait pour réparer le script et que j'isole dans une PR à part pour que ce soit mergé plus vite que les trucs qui doivent attendre
> feat(tools): #3215 mettre à jour routes osiris dans le script

- packages/api/src/interfaces/http/Admin.http.ts
- packages/api/src/interfaces/http/User.http.ts
- packages/api/tests/interfaces/http/__snapshots__/admin.spec.ts.snap
- packages/api/tests/interfaces/http/admin.spec.ts
- packages/api/tests/modules/user/__snapshots__/user.spec.ts.snap
- packages/api/tests/modules/user/user.spec.ts
- packages/front/src/routes/admin/admin.service.js
missing : 
- doit adapter les appels du front
- réparer tests integ
> refactor(api): #3220 extract admin user routes to admin controller

- packages/front/src/routes/etablissement/[identifier]/components/ContactEtab/ContactEtabController.js
> fix(front): #3209 use new header getter

- packages/api/src/cron.ts
- packages/api/src/dataProviders/db/providers/dauphin/dauphin-gispro.port.ts
> feat(api): #3237 hide confusing dauphin 2023 data

- packages/front/src/lib/components/Header/Header.svelte
- packages/front/src/lib/resources/auth/auth.service.js
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/lib/resources/users/user.service.ts
- packages/front/src/routes/auth/activate/[token]/ActivateAccount.controller.js
- packages/front/src/routes/auth/activate/[token]/ActivateAccount.controller.test.js
- packages/front/src/routes/auth/reset-password/[token]/ResetPwd.controller.js
- packages/front/src/routes/auth/reset-password/[token]/ResetPwd.controller.test.js
> refactor(front): #1567 reactive login and logout

- packages/api/migrations/20250318095226-chorus_exercise_as_number.js
- packages/api/src/dataProviders/db/dataViz/amountVSProgramRegion/amountsVsProgramRegion.port.ts
- packages/api/src/interfaces/cli/AmountsVsProgramRegion.cli.ts
- packages/api/src/interfaces/cli/PaymentFlat.cli.ts
- packages/api/src/modules/paymentFlat/paymentFlat.service.ts
- packages/api/src/modules/providers/chorus/entities/ChorusLineEntity.ts
- packages/api/tests/interfaces/cli/amountsVsProgramRegionInterfaceCli.spec.ts
closes #3219
En version sale juste par exercice ç'a l'air de marcher (même si c'est assez lent)
Je suis tentée de quand même optimiser en flux plutôt que juste par exercice mais c'est pas ce qu'on s'était dit. C'est juste à cause de ce doute que je laisse la PR en draft
EDIT : non on n'en fait pas plus ce coup-ci
> perf(api): #3219 optimize payment flat

- .github/workflows/main.yml
> feat(ci): #3243 upgrade ubuntu version

- packages/api/src/dataProviders/db/providers/fonjep/dbo/FonjepVersementDbo.ts
- packages/api/src/dataProviders/db/providers/fonjep/dbo/fonjepDispositifDbo.ts
- packages/api/src/dataProviders/db/providers/fonjep/dbo/fonjepPosteDbo.ts
- packages/api/src/dataProviders/db/providers/fonjep/dbo/fonjepTiersDbo.ts
- packages/api/src/dataProviders/db/providers/fonjep/dbo/fonjepTypePosteDbo.ts
- packages/api/src/dataProviders/db/providers/fonjep/fonjepDboAdapter.ts
> refactor(api): #3284 fonjep create dbo from entities

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/api/CHANGELOG.md
- packages/api/package.json
- packages/api/src/modules/user/services/agentConnect/user.agentConnect.service.test.ts
- packages/api/src/modules/user/services/agentConnect/user.agentConnect.service.ts
> fix(api): normalize proconnect email to lowercase

- package-lock.json
- packages/api/package.json
- packages/api/src/middlewares/LogMiddleware.ts
- packages/api/src/modules/providers/dauphin/dauphin.service.test.ts
- packages/core/package.json
- packages/dto/package.json
- packages/front/package.json
> chore: #3354 bump to typescript 5.5

- packages/api/src/modules/user/services/activation/user.activation.service.ts
- packages/dto/auth/ResetPasswordDtoResponse.ts
- packages/front/src/lib/resources/auth/auth.service.test.js
- packages/front/src/routes/auth/forget-password/+page.svelte
- packages/front/src/routes/auth/forget-password/ForgetPwd.controller.js
> feat(front, api)): #3329 pro connect no reset pwd

- packages/api/src/modules/providers/apiAsso/apiAsso.service.test.ts
- packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> fix(api): #3366 compensate weird api asso formats

- packages/api/src/middlewares/headersMiddleware.ts
- packages/front/src/hooks.server.ts
> fix(api, front): #3380 remove warning on HTTP Header max-age

- packages/api/src/shared/MongoConnection.ts
> refactor(api): #3401 disable mongodb start logs in dev mode

- packages/api/src/modules/paymentFlat/paymentFlat.chorus.service.test.ts
- packages/api/src/modules/paymentFlat/paymentFlat.chorus.service.ts
- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.test.ts
- packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.ts
- packages/api/src/modules/providers/chorus/adapters/__snapshots__/ChorusAdapter.test.ts.snap
- packages/api/src/modules/providers/dataBretagne/dataBretagne.service.test.ts
- packages/api/src/modules/providers/dataBretagne/dataBretagne.service.ts
> refactor(api): #3400 minor updates on chorus payment flat process

- packages/api/src/interfaces/cli/Scdl.cli.ts
- packages/api/src/modules/providers/chorus/chorus.parser.test.ts
- packages/api/src/modules/providers/chorus/chorus.parser.ts
- packages/api/src/modules/providers/fonjep/adapters/FonjepEntityAdapter.ts
- packages/api/src/modules/providers/fonjep/adapters/__snapshots__/FonjepEntityAdapter.test.ts.snap
- packages/api/tests/modules/providers/fonjep/__snapshots__/fonjepCli.spec.ts.snap
> feat(api): #3397 add producer slug to payment flat unique id

- packages/api/src/shared/GenericParser.test.ts
- packages/api/src/shared/GenericParser.ts
> fix(api): #3451 do not convert cell value equal to  0 to null

- packages/api/src/dataProviders/db/paymentFlat/paymentFlat.port.ts
- packages/api/src/dataProviders/db/providers/fonjep/fonjep.payment.port.old.ts
> fix(api): #3553 fix payment duplicate collection name and disable payment flat for fonjep

- packages/api/src/modules/providers/scdl/scdl.grant.parser.test.ts
- packages/api/src/modules/providers/scdl/scdl.grant.parser.ts
- packages/api/src/modules/providers/scdl/scdl.mapper.test.ts
- packages/api/src/modules/providers/scdl/scdl.mapper.ts
clarifie et simplifie le pb rencontré par Louis ici https://mattermost.incubateur.net/betagouv/pl/mgt9m3yoypr95dkbu9msobe9so
> feat(api): #0000 scdl mapper removes spaces in siret

- packages/api/src/modules/providers/fonjep/fonjep.service.old.ts
- packages/api/tests/interfaces/http/__snapshots__/associations.spec.ts.snap
> refactor(api): #3563 remove EtablissementProvider from fonjep

- packages/api/src/interfaces/cli/User.cli.test.ts
- packages/api/src/interfaces/cli/User.cli.ts
- packages/api/src/modules/user/services/activation/user.activation.service.test.ts
- packages/api/src/modules/user/services/activation/user.activation.service.ts
- packages/api/src/modules/user/services/stats/user.stats.service.ts
- packages/api/tests/modules/user/__snapshots__/user.spec.ts.snap
- packages/api/tests/modules/user/user.spec.ts
> refactor(api): #3490 clean user cli replace by http and createAdmin cmd

- packages/api/src/dataProviders/db/applicationFlat/ApplicationFlatDbo.ts
- packages/api/src/entities/ApplicationFlatEntity.ts
- packages/api/src/modules/providers/dauphin-gispro/adapters/DauphinDtoAdapter.ts
je revert le N/A sur granted amount comme communiqué sur mattermost + le schéma de mapping
> feat(api): #0000 revert not applicable granted amount
